member(obj1, 'url', '@id') .
member(obj1, 'a', '@type') .
member(obj1, 'name', 'http://xmlns.com/foaf/0.1/name') .
member(obj0, '@context', obj1) .
member(obj0, 'url', 'http://example.com/about#gregg') .
member(obj0, 'a', 'http://xmlns.com/foaf/0.1/Person') .
member(obj0, 'name', 'Gregg Kellogg') .
root('alias.jsonld', obj0) .
member(obj3, '@base', 'http://example.com/document.jsonld') .
member(obj2, '@context', obj3) .
member(obj2, '@id', '') .
member(obj2, 'label', 'Just a simple document') .
root('base-uri-ctx.jsonld', obj2) .
member(obj5, 'label', 'http://www.w3.org/2000/01/rdf-schema#label') .
member(obj4, '@context', obj5) .
member(obj4, '@id', '') .
member(obj4, 'label', 'Just a simple document') .
root('base-uri.jsonld', obj4) .
member(obj7, 0, 'http://json-ld.org/contexts/person.jsonld') .
member(obj8, 'pic', 'http://xmlns.com/foaf/0.1/depiction') .
member(obj7, 1, obj8) .
member(obj6, '@context', obj7) .
member(obj6, 'name', 'Manu Sporny') .
member(obj6, 'homepage', 'http://manu.sporny.org/') .
member(obj6, 'pic', 'http://twitter.com/account/profile_image/manusporny') .
root('combined-ctx.jsonld', obj6) .
member(obj10, 'name', 'http://schema.org/name') .
member(obj11, '@id', 'http://schema.org/image') .
member(obj11, '@type', '@id') .
member(obj10, 'image', obj11) .
member(obj12, '@id', 'http://schema.org/url') .
member(obj12, '@type', '@id') .
member(obj10, 'homepage', obj12) .
member(obj9, '@context', obj10) .
member(obj9, 'name', 'Manu Sporny') .
member(obj9, 'homepage', 'http://manu.sporny.org/') .
member(obj9, 'image', 'http://manu.sporny.org/images/manu.png') .
root('ctx-inline.jsonld', obj9) .
member(obj13, '@context', 'http://json-ld.org/contexts/person.jsonld') .
member(obj13, 'name', 'Manu Sporny') .
member(obj13, 'homepage', 'http://manu.sporny.org/') .
member(obj13, 'image', 'http://manu.sporny.org/images/manu.png') .
root('ctx-remote.jsonld', obj13) .
member(obj15, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj15, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj16, '@type', '@id') .
member(obj15, 'foaf:homepage', obj16) .
member(obj17, '@id', 'foaf:depiction') .
member(obj17, '@type', '@id') .
member(obj15, 'picture', obj17) .
member(obj14, '@context', obj15) .
member(obj14, '@id', 'http://me.markus-lanthaler.com/') .
member(obj14, '@type', 'foaf:Person') .
member(obj14, 'foaf:name', 'Markus Lanthaler') .
member(obj14, 'foaf:homepage', 'http://www.markus-lanthaler.com/') .
member(obj14, 'picture', 'http://twitter.com/account/profile_image/markuslanthaler') .
root('curie-ctx.jsonld', obj14) .
member(obj19, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj18, '@context', obj19) .
member(obj18, '@type', 'foaf:Person') .
member(obj18, 'foaf:name', 'Dave Longley') .
root('curie.jsonld', obj18) .
member(obj21, 'Person', 'http://xmlns.com/foaf/0.1/Person') .
member(obj21, 'name', 'http://xmlns.com/foaf/0.1/name') .
member(obj21, 'knows', 'http://xmlns.com/foaf/0.1/knows') .
member(obj20, '@context', obj21) .
member(obj23, '@id', 'http://manu.sporny.org/about#manu') .
member(obj23, '@type', 'foaf:Person') .
member(obj23, 'name', 'Manu Sporny') .
member(obj23, 'knows', 'http://greggkellogg.net/foaf#me') .
member(obj22, 0, obj23) .
member(obj24, '@id', 'http://greggkellogg.net/foaf#me') .
member(obj24, '@type', 'foaf:Person') .
member(obj24, 'name', 'Gregg Kellogg') .
member(obj24, 'knows', 'http://manu.sporny.org/about#manu') .
member(obj22, 1, obj24) .
member(obj20, '@graph', obj22) .
root('default-graph.jsonld', obj20) .
member(obj26, 'name', 'http://schema.org/name') .
member(obj26, 'Person', 'http://schema.org/Person') .
member(obj26, 'knows', 'http://xmlns.com/foaf/0.1/knows') .
member(obj25, '@context', obj26) .
member(obj25, 'name', 'Manu Sporny') .
member(obj27, '@type', 'Person') .
member(obj27, 'name', 'Gregg Kellogg') .
member(obj25, 'knows', obj27) .
root('embedding.jsonld', obj25) .
member(obj29, 'schema', 'http://schema.org/') .
member(obj29, 'name', 'schema:name') .
member(obj29, 'body', 'schema:articleBody') .
member(obj29, 'words', 'schema:wordCount') .
member(obj30, '@id', 'schema:blogPost') .
member(obj30, '@container', '@index') .
member(obj29, 'post', obj30) .
member(obj28, '@context', obj29) .
member(obj28, '@id', 'http://example.com/') .
member(obj28, '@type', 'schema:Blog') .
member(obj28, 'name', 'World Financial News') .
member(obj32, '@id', 'http://example.com/posts/1/en') .
member(obj32, 'body', 'World commodities were up today with heavy trading of crude oil...') .
member(obj32, 'words', 1539) .
member(obj31, 'en', obj32) .
member(obj33, '@id', 'http://example.com/posts/1/de') .
member(obj33, 'body', 'Die Werte an Warenbörsen stiegen im Sog eines starken Handels von Rohöl...') .
member(obj33, 'words', 1204) .
member(obj31, 'de', obj33) .
member(obj28, 'post', obj31) .
root('index.jsonld', obj28) .
member(obj34, 'http://schema.org/name', 'Manu Sporny') .
member(obj35, '@id', 'http://manu.sporny.org/') .
member(obj34, 'http://schema.org/url', obj35) .
member(obj36, '@id', 'http://manu.sporny.org/images/manu.png') .
member(obj34, 'http://schema.org/image', obj36) .
root('intro.jsonld', obj34) .
member(obj38, 'name', 'http://schema.org/name') .
member(obj37, '@context', obj38) .
member(obj37, 'name', 'Manu Sporny') .
member(obj37, 'status', 'trollin') .
root('iris-ignored.jsonld', obj37) .
member(obj41, '@id', 'http://xmlns.com/foaf/0.1/nick') .
member(obj41, '@container', '@list') .
member(obj40, 'nick', obj41) .
member(obj39, '@context', obj40) .
member(obj39, '@id', 'http://example.org/people#joebob') .
member(obj42, 0, 'joe') .
member(obj42, 1, 'bob') .
member(obj42, 2, 'jaybee') .
member(obj39, 'nick', obj42) .
root('list-ctx.jsonld', obj39) .
member(obj44, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj43, '@context', obj44) .
member(obj43, '@id', 'http://example.org/people#joebob') .
member(obj46, 0, 'joe') .
member(obj46, 1, 'bob') .
member(obj46, 2, 'jaybee') .
member(obj45, '@list', obj46) .
member(obj43, 'foaf:nick', obj45) .
root('list.jsonld', obj43) .
member(obj48, '@context', 'http://example.org/contexts/person.jsonld') .
member(obj48, 'name', 'Manu Sporny') .
member(obj48, 'homepage', 'http://manu.sporny.org/') .
member(obj48, 'depiction', 'http://twitter.com/account/profile_image/manusporny') .
member(obj47, 0, obj48) .
member(obj49, '@context', 'http://example.org/contexts/place.jsonld') .
member(obj49, 'name', 'The Empire State Building') .
member(obj49, 'description', 'The Empire State Building is a 102-story landmark in New York City.') .
member(obj50, 'latitude', '40.75') .
member(obj50, 'longitude', '73.98') .
member(obj49, 'geo', obj50) .
member(obj47, 1, obj49) .
root('multi-ctx.jsonld', obj47) .
member(obj52, 'dc', 'http://purl.org/dc/terms/') .
member(obj51, '@context', obj52) .
member(obj51, '@id', 'http://example.org/articles/8') .
member(obj54, '@value', 'Das Kapital') .
member(obj54, '@language', 'de') .
member(obj53, 0, obj54) .
member(obj55, '@value', 'Capital') .
member(obj55, '@language', 'en') .
member(obj53, 1, obj55) .
member(obj51, 'dc:title', obj53) .
root('multi-expanded-values.jsonld', obj51) .
member(obj57, 'nick', 'http://xmlns.com/foaf/0.1/nick') .
member(obj56, '@context', obj57) .
member(obj56, '@id', 'http://example.org/people#joebob') .
member(obj58, 0, 'joe') .
member(obj58, 1, 'bob') .
member(obj58, 2, 'JB') .
member(obj56, 'nick', obj58) .
root('multi-values.jsonld', obj56) .
member(obj61, '@id', 'http://www.w3.org/ns/prov#generatedAtTime') .
member(obj61, '@type', 'http://www.w3.org/2001/XMLSchema#date') .
member(obj60, 'generatedAt', obj61) .
member(obj60, 'Person', 'http://xmlns.com/foaf/0.1/Person') .
member(obj60, 'name', 'http://xmlns.com/foaf/0.1/name') .
member(obj60, 'knows', 'http://xmlns.com/foaf/0.1/knows') .
member(obj59, '@context', obj60) .
member(obj59, '@id', 'http://example.org/graphs/73') .
member(obj59, 'generatedAt', '2012-04-09') .
member(obj63, '@id', 'http://manu.sporny.org/about#manu') .
member(obj63, '@type', 'Person') .
member(obj63, 'name', 'Manu Sporny') .
member(obj63, 'knows', 'http://greggkellogg.net/foaf#me') .
member(obj62, 0, obj63) .
member(obj64, '@id', 'http://greggkellogg.net/foaf#me') .
member(obj64, '@type', 'Person') .
member(obj64, 'name', 'Gregg Kellogg') .
member(obj64, 'knows', 'http://manu.sporny.org/about#manu') .
member(obj62, 1, obj64) .
member(obj59, '@graph', obj62) .
root('named-graph.jsonld', obj59) .
member(obj66, 'name', 'http://schema.org/name') .
member(obj65, '@context', obj66) .
member(obj65, '@id', 'http://me.markus-lanthaler.com/') .
member(obj65, 'name', 'Markus Lanthaler') .
root('node-id.jsonld', obj65) .
member(obj68, 'Person', 'http://schema.org/Person') .
member(obj68, 'name', 'http://schema.org/name') .
member(obj68, 'jobTitle', 'http://schema.org/jobTitle') .
member(obj68, 'telephone', 'http://schema.org/telephone') .
member(obj69, '@id', 'http://schema.org/url') .
member(obj69, '@type', '@id') .
member(obj68, 'url', obj69) .
member(obj67, '@context', obj68) .
member(obj67, '@type', 'Person') .
member(obj67, 'name', 'Jane Doe') .
member(obj67, 'jobTitle', 'Professor') .
member(obj67, 'telephone', '(425) 123-4567') .
member(obj67, 'url', 'http://www.janedoe.com') .
root('person.jsonld', obj67) .
member(obj71, 'name', 'http://example.com/vocab#name') .
member(obj72, '@reverse', 'http://example.com/vocab#parent') .
member(obj71, 'children', obj72) .
member(obj70, '@context', obj71) .
member(obj70, '@id', '#homer') .
member(obj70, 'name', 'Homer') .
member(obj74, '@id', '#bart') .
member(obj74, 'name', 'Bart') .
member(obj73, 0, obj74) .
member(obj75, '@id', '#lisa') .
member(obj75, 'name', 'Lisa') .
member(obj73, 1, obj75) .
member(obj70, 'children', obj73) .
root('reverse-ctx.jsonld', obj70) .
member(obj76, '@id', '#homer') .
member(obj76, 'http://example.com/vocab#name', 'Homer') .
member(obj79, '@id', '#bart') .
member(obj79, 'http://example.com/vocab#name', 'Bart') .
member(obj78, 0, obj79) .
member(obj80, '@id', '#lisa') .
member(obj80, 'http://example.com/vocab#name', 'Lisa') .
member(obj78, 1, obj80) .
member(obj77, 'http://example.com/vocab#parent', obj78) .
member(obj76, '@reverse', obj77) .
root('reverse.jsonld', obj76) .
member(obj82, 'name', 'http://example.com/person#name') .
member(obj82, 'details', 'http://example.com/person#details') .
member(obj81, '@context', obj82) .
member(obj81, 'name', 'Markus Lanthaler') .
member(obj84, 'name', 'http://example.com/organization#name') .
member(obj83, '@context', obj84) .
member(obj83, 'name', 'Graz University of Technology') .
member(obj81, 'details', obj83) .
root('scoped-ctx.jsonld', obj81) .
member(obj86, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj86, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj86, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj86, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj86, 'rdfs', 'http://www.w3.org/2000/01/rdf-schema#') .
member(obj86, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj87, '@id', 'http://purl.org/dc/terms/license') .
member(obj86, 'license', obj87) .
member(obj86, 'id', '@id') .
member(obj88, '@id', 'td:hasPropertyAffordance') .
member(obj88, '@type', '@id') .
member(obj88, '@container', '@index') .
member(obj89, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj89, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj89, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj89, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj89, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj90, '@id', 'jsonschema:DataSchema') .
member(obj89, 'DataSchema', obj90) .
member(obj91, '@id', 'jsonschema:readOnly') .
member(obj91, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj89, 'readOnly', obj91) .
member(obj92, '@id', 'jsonschema:writeOnly') .
member(obj92, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj89, 'writeOnly', obj92) .
member(obj93, '@id', 'jsonschema:maximum') .
member(obj89, 'maximum', obj93) .
member(obj94, '@id', 'jsonschema:minimum') .
member(obj89, 'minimum', obj94) .
member(obj95, '@id', 'jsonschema:maxItems') .
member(obj95, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj89, 'maxItems', obj95) .
member(obj96, '@id', 'jsonschema:minItems') .
member(obj96, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj89, 'minItems', obj96) .
member(obj97, '@id', 'jsonschema:items') .
member(obj97, '@type', '@id') .
member(obj89, 'items', obj97) .
member(obj98, '@id', 'jsonschema:required') .
member(obj98, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj98, '@container', '@set') .
member(obj89, 'required', obj98) .
member(obj99, '@id', 'jsonschema:enum') .
member(obj99, '@type', '@id') .
member(obj99, '@container', '@set') .
member(obj89, 'enum', obj99) .
member(obj100, '@id', 'jsonschema:const') .
member(obj89, 'const', obj100) .
member(obj101, '@id', 'jsonschema:unit') .
member(obj89, 'unit', obj101) .
member(obj102, '@id', 'jsonschema:oneOf') .
member(obj102, '@container', '@set') .
member(obj89, 'oneOf', obj102) .
member(obj103, '@id', 'rdf:type') .
member(obj103, '@type', '@vocab') .
member(obj89, 'type', obj103) .
member(obj89, 'object', 'jsonschema:ObjectSchema') .
member(obj89, 'array', 'jsonschema:ArraySchema') .
member(obj89, 'boolean', 'jsonschema:BooleanSchema') .
member(obj89, 'string', 'jsonschema:StringSchema') .
member(obj89, 'number', 'jsonschema:NumberSchema') .
member(obj89, 'integer', 'jsonschema:IntegerSchema') .
member(obj89, 'null', 'jsonschema:NullSchema') .
member(obj104, '@id', 'jsonschema:properties') .
member(obj104, '@type', '@id') .
member(obj104, '@container', '@index') .
member(obj89, 'properties', obj104) .
member(obj88, '@context', obj89) .
member(obj86, 'properties', obj88) .
member(obj105, '@id', 'td:hasActionAffordance') .
member(obj105, '@type', '@id') .
member(obj105, '@container', '@index') .
member(obj86, 'actions', obj105) .
member(obj106, '@id', 'td:hasEventAffordance') .
member(obj106, '@type', '@id') .
member(obj106, '@container', '@index') .
member(obj86, 'events', obj106) .
member(obj107, '@id', 'td:hasSecurityConfiguration') .
member(obj107, '@type', '@id') .
member(obj107, '@container', '@set') .
member(obj108, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj108, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj108, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj108, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj108, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj109, '@id', 'wotsec:in') .
member(obj108, 'in', obj109) .
member(obj110, '@id', 'wotsec:authorization') .
member(obj108, 'authorization', obj110) .
member(obj111, '@id', 'wotsec:token') .
member(obj108, 'token', obj111) .
member(obj112, '@id', 'wotsec:refresh') .
member(obj108, 'refresh', obj112) .
member(obj113, '@id', 'wotsec:proxy') .
member(obj108, 'proxy', obj113) .
member(obj114, '@id', 'wotsec:scopes') .
member(obj114, '@container', '@set') .
member(obj108, 'scopes', obj114) .
member(obj115, '@id', 'wotsec:flow') .
member(obj108, 'flow', obj115) .
member(obj116, '@id', 'wotsec:qop') .
member(obj108, 'qop', obj116) .
member(obj117, '@id', 'wotsec:alg') .
member(obj108, 'alg', obj117) .
member(obj118, '@id', 'wotsec:format') .
member(obj108, 'format', obj118) .
member(obj119, '@id', 'wotsec:identity') .
member(obj108, 'identity', obj119) .
member(obj120, '@id', 'rdf:type') .
member(obj120, '@type', '@vocab') .
member(obj108, 'scheme', obj120) .
member(obj108, 'nosec', 'wotsec:NoSecurityScheme') .
member(obj108, 'basic', 'wotsec:BasicSecurityScheme') .
member(obj108, 'digest', 'wotsec:DigestSecurityScheme') .
member(obj108, 'apikey', 'wotsec:APIKeySecurityScheme') .
member(obj108, 'bearer', 'wotsec:BearerSecurityScheme') .
member(obj108, 'cert', 'wotsec:CertSecurityScheme') .
member(obj108, 'psk', 'wotsec:PSKSecurityScheme') .
member(obj108, 'public', 'wotsec:PublicSecurityScheme') .
member(obj108, 'pop', 'wotsec:PoPSecurityScheme') .
member(obj108, 'oauth2', 'wotsec:OAuth2SecurityScheme') .
member(obj107, '@context', obj108) .
member(obj86, 'security', obj107) .
member(obj121, '@id', 'td:securityDefinitions') .
member(obj121, '@type', '@id') .
member(obj121, '@container', '@index') .
member(obj86, 'securityDefinitions', obj121) .
member(obj122, '@id', 'td:Thing') .
member(obj86, 'Thing', obj122) .
member(obj123, '@id', 'td:EventAffordance') .
member(obj86, 'EventAffordance', obj123) .
member(obj124, '@id', 'td:baseUri') .
member(obj124, '@type', 'xsd:anyURI') .
member(obj86, 'base', obj124) .
member(obj125, '@id', 'td:name') .
member(obj86, 'name', obj125) .
member(obj126, '@id', 'td:created') .
member(obj86, 'created', obj126) .
member(obj127, '@id', 'td:modified') .
member(obj86, 'modified', obj127) .
member(obj128, '@id', 'td:isObservable') .
member(obj128, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj86, 'observable', obj128) .
member(obj129, '@id', 'td:VersionInfo') .
member(obj86, 'VersionInfo', obj129) .
member(obj130, '@id', 'td:PropertyAffordance') .
member(obj86, 'PropertyAffordance', obj130) .
member(obj131, '@id', 'td:hasForm') .
member(obj131, '@type', '@id') .
member(obj131, '@container', '@set') .
member(obj132, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj132, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj132, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj132, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj132, 'rdfs', 'http://www.w3.org/2000/01/rdf-schema#') .
member(obj132, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj133, '@id', 'hyperm:Link') .
member(obj132, 'Link', obj133) .
member(obj134, '@id', 'hyperm:Form') .
member(obj132, 'Form', obj134) .
member(obj135, '@id', 'hyperm:forOperationType') .
member(obj135, '@container', '@set') .
member(obj132, 'op', obj135) .
member(obj136, '@id', 'hyperm:forSubProtocol') .
member(obj132, 'subprotocol', obj136) .
member(obj137, '@id', 'hyperm:forContentType') .
member(obj137, '@type', 'xsd:string') .
member(obj132, 'contentType', obj137) .
member(obj138, '@id', 'hyperm:forContentCoding') .
member(obj138, '@type', 'xsd:string') .
member(obj132, 'contentCoding', obj138) .
member(obj139, '@id', 'hyperm:hasAnchor') .
member(obj132, 'anchor', obj139) .
member(obj140, '@id', 'hyperm:hasTarget') .
member(obj132, 'href', obj140) .
member(obj141, '@id', 'hyperm:hasRelationType') .
member(obj132, 'rel', obj141) .
member(obj142, '@id', 'hyperm:hintsAtMediaType') .
member(obj132, 'type', obj142) .
member(obj143, '@id', 'hyperm:returns') .
member(obj132, 'response', obj143) .
member(obj131, '@context', obj132) .
member(obj86, 'forms', obj131) .
member(obj144, '@id', 'td:versionInfo') .
member(obj144, '@type', '@id') .
member(obj86, 'version', obj144) .
member(obj145, '@id', 'td:hasLink') .
member(obj145, '@type', '@id') .
member(obj145, '@container', '@set') .
member(obj146, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj146, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj146, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj146, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj146, 'rdfs', 'http://www.w3.org/2000/01/rdf-schema#') .
member(obj146, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj147, '@id', 'hyperm:Link') .
member(obj146, 'Link', obj147) .
member(obj148, '@id', 'hyperm:Form') .
member(obj146, 'Form', obj148) .
member(obj149, '@id', 'hyperm:forOperationType') .
member(obj149, '@container', '@set') .
member(obj146, 'op', obj149) .
member(obj150, '@id', 'hyperm:forSubProtocol') .
member(obj146, 'subprotocol', obj150) .
member(obj151, '@id', 'hyperm:forContentType') .
member(obj151, '@type', 'xsd:string') .
member(obj146, 'contentType', obj151) .
member(obj152, '@id', 'hyperm:forContentCoding') .
member(obj152, '@type', 'xsd:string') .
member(obj146, 'contentCoding', obj152) .
member(obj153, '@id', 'hyperm:hasAnchor') .
member(obj146, 'anchor', obj153) .
member(obj154, '@id', 'hyperm:hasTarget') .
member(obj146, 'href', obj154) .
member(obj155, '@id', 'hyperm:hasRelationType') .
member(obj146, 'rel', obj155) .
member(obj156, '@id', 'hyperm:hintsAtMediaType') .
member(obj146, 'type', obj156) .
member(obj157, '@id', 'hyperm:returns') .
member(obj146, 'response', obj157) .
member(obj145, '@context', obj146) .
member(obj86, 'links', obj145) .
member(obj158, '@id', 'td:hasUriTemplateVariable') .
member(obj158, '@container', '@index') .
member(obj86, 'uriVariables', obj158) .
member(obj159, '@id', 'td:isSafe') .
member(obj86, 'safe', obj159) .
member(obj160, '@id', 'td:isIdempotent') .
member(obj86, 'idempotent', obj160) .
member(obj161, '@id', 'td:instance') .
member(obj86, 'instance', obj161) .
member(obj162, '@id', 'td:InteractionAffordance') .
member(obj86, 'InteractionAffordance', obj162) .
member(obj163, '@id', 'td:ActionAffordance') .
member(obj86, 'ActionAffordance', obj163) .
member(obj164, '@id', 'td:hasInputSchema') .
member(obj164, '@type', '@id') .
member(obj165, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj165, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj165, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj165, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj165, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj166, '@id', 'jsonschema:DataSchema') .
member(obj165, 'DataSchema', obj166) .
member(obj167, '@id', 'jsonschema:readOnly') .
member(obj167, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj165, 'readOnly', obj167) .
member(obj168, '@id', 'jsonschema:writeOnly') .
member(obj168, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj165, 'writeOnly', obj168) .
member(obj169, '@id', 'jsonschema:maximum') .
member(obj165, 'maximum', obj169) .
member(obj170, '@id', 'jsonschema:minimum') .
member(obj165, 'minimum', obj170) .
member(obj171, '@id', 'jsonschema:maxItems') .
member(obj171, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj165, 'maxItems', obj171) .
member(obj172, '@id', 'jsonschema:minItems') .
member(obj172, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj165, 'minItems', obj172) .
member(obj173, '@id', 'jsonschema:items') .
member(obj173, '@type', '@id') .
member(obj165, 'items', obj173) .
member(obj174, '@id', 'jsonschema:required') .
member(obj174, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj174, '@container', '@set') .
member(obj165, 'required', obj174) .
member(obj175, '@id', 'jsonschema:enum') .
member(obj175, '@type', '@id') .
member(obj175, '@container', '@set') .
member(obj165, 'enum', obj175) .
member(obj176, '@id', 'jsonschema:const') .
member(obj165, 'const', obj176) .
member(obj177, '@id', 'jsonschema:unit') .
member(obj165, 'unit', obj177) .
member(obj178, '@id', 'jsonschema:oneOf') .
member(obj178, '@container', '@set') .
member(obj165, 'oneOf', obj178) .
member(obj179, '@id', 'rdf:type') .
member(obj179, '@type', '@vocab') .
member(obj165, 'type', obj179) .
member(obj165, 'object', 'jsonschema:ObjectSchema') .
member(obj165, 'array', 'jsonschema:ArraySchema') .
member(obj165, 'boolean', 'jsonschema:BooleanSchema') .
member(obj165, 'string', 'jsonschema:StringSchema') .
member(obj165, 'number', 'jsonschema:NumberSchema') .
member(obj165, 'integer', 'jsonschema:IntegerSchema') .
member(obj165, 'null', 'jsonschema:NullSchema') .
member(obj180, '@id', 'jsonschema:properties') .
member(obj180, '@type', '@id') .
member(obj180, '@container', '@index') .
member(obj165, 'properties', obj180) .
member(obj164, '@context', obj165) .
member(obj86, 'input', obj164) .
member(obj181, '@id', 'td:hasOutputSchema') .
member(obj181, '@type', '@id') .
member(obj182, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj182, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj182, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj182, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj182, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj183, '@id', 'jsonschema:DataSchema') .
member(obj182, 'DataSchema', obj183) .
member(obj184, '@id', 'jsonschema:readOnly') .
member(obj184, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj182, 'readOnly', obj184) .
member(obj185, '@id', 'jsonschema:writeOnly') .
member(obj185, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj182, 'writeOnly', obj185) .
member(obj186, '@id', 'jsonschema:maximum') .
member(obj182, 'maximum', obj186) .
member(obj187, '@id', 'jsonschema:minimum') .
member(obj182, 'minimum', obj187) .
member(obj188, '@id', 'jsonschema:maxItems') .
member(obj188, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj182, 'maxItems', obj188) .
member(obj189, '@id', 'jsonschema:minItems') .
member(obj189, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj182, 'minItems', obj189) .
member(obj190, '@id', 'jsonschema:items') .
member(obj190, '@type', '@id') .
member(obj182, 'items', obj190) .
member(obj191, '@id', 'jsonschema:required') .
member(obj191, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj191, '@container', '@set') .
member(obj182, 'required', obj191) .
member(obj192, '@id', 'jsonschema:enum') .
member(obj192, '@type', '@id') .
member(obj192, '@container', '@set') .
member(obj182, 'enum', obj192) .
member(obj193, '@id', 'jsonschema:const') .
member(obj182, 'const', obj193) .
member(obj194, '@id', 'jsonschema:unit') .
member(obj182, 'unit', obj194) .
member(obj195, '@id', 'jsonschema:oneOf') .
member(obj195, '@container', '@set') .
member(obj182, 'oneOf', obj195) .
member(obj196, '@id', 'rdf:type') .
member(obj196, '@type', '@vocab') .
member(obj182, 'type', obj196) .
member(obj182, 'object', 'jsonschema:ObjectSchema') .
member(obj182, 'array', 'jsonschema:ArraySchema') .
member(obj182, 'boolean', 'jsonschema:BooleanSchema') .
member(obj182, 'string', 'jsonschema:StringSchema') .
member(obj182, 'number', 'jsonschema:NumberSchema') .
member(obj182, 'integer', 'jsonschema:IntegerSchema') .
member(obj182, 'null', 'jsonschema:NullSchema') .
member(obj197, '@id', 'jsonschema:properties') .
member(obj197, '@type', '@id') .
member(obj197, '@container', '@index') .
member(obj182, 'properties', obj197) .
member(obj181, '@context', obj182) .
member(obj86, 'output', obj181) .
member(obj198, '@id', 'td:hasSubscriptionSchema') .
member(obj198, '@type', '@id') .
member(obj199, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj199, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj199, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj199, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj199, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj200, '@id', 'jsonschema:DataSchema') .
member(obj199, 'DataSchema', obj200) .
member(obj201, '@id', 'jsonschema:readOnly') .
member(obj201, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj199, 'readOnly', obj201) .
member(obj202, '@id', 'jsonschema:writeOnly') .
member(obj202, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj199, 'writeOnly', obj202) .
member(obj203, '@id', 'jsonschema:maximum') .
member(obj199, 'maximum', obj203) .
member(obj204, '@id', 'jsonschema:minimum') .
member(obj199, 'minimum', obj204) .
member(obj205, '@id', 'jsonschema:maxItems') .
member(obj205, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj199, 'maxItems', obj205) .
member(obj206, '@id', 'jsonschema:minItems') .
member(obj206, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj199, 'minItems', obj206) .
member(obj207, '@id', 'jsonschema:items') .
member(obj207, '@type', '@id') .
member(obj199, 'items', obj207) .
member(obj208, '@id', 'jsonschema:required') .
member(obj208, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj208, '@container', '@set') .
member(obj199, 'required', obj208) .
member(obj209, '@id', 'jsonschema:enum') .
member(obj209, '@type', '@id') .
member(obj209, '@container', '@set') .
member(obj199, 'enum', obj209) .
member(obj210, '@id', 'jsonschema:const') .
member(obj199, 'const', obj210) .
member(obj211, '@id', 'jsonschema:unit') .
member(obj199, 'unit', obj211) .
member(obj212, '@id', 'jsonschema:oneOf') .
member(obj212, '@container', '@set') .
member(obj199, 'oneOf', obj212) .
member(obj213, '@id', 'rdf:type') .
member(obj213, '@type', '@vocab') .
member(obj199, 'type', obj213) .
member(obj199, 'object', 'jsonschema:ObjectSchema') .
member(obj199, 'array', 'jsonschema:ArraySchema') .
member(obj199, 'boolean', 'jsonschema:BooleanSchema') .
member(obj199, 'string', 'jsonschema:StringSchema') .
member(obj199, 'number', 'jsonschema:NumberSchema') .
member(obj199, 'integer', 'jsonschema:IntegerSchema') .
member(obj199, 'null', 'jsonschema:NullSchema') .
member(obj214, '@id', 'jsonschema:properties') .
member(obj214, '@type', '@id') .
member(obj214, '@container', '@index') .
member(obj199, 'properties', obj214) .
member(obj198, '@context', obj199) .
member(obj86, 'subscription', obj198) .
member(obj215, '@id', 'td:hasNotificationSchema') .
member(obj215, '@type', '@id') .
member(obj216, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj216, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj216, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj216, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj216, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj217, '@id', 'jsonschema:DataSchema') .
member(obj216, 'DataSchema', obj217) .
member(obj218, '@id', 'jsonschema:readOnly') .
member(obj218, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj216, 'readOnly', obj218) .
member(obj219, '@id', 'jsonschema:writeOnly') .
member(obj219, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj216, 'writeOnly', obj219) .
member(obj220, '@id', 'jsonschema:maximum') .
member(obj216, 'maximum', obj220) .
member(obj221, '@id', 'jsonschema:minimum') .
member(obj216, 'minimum', obj221) .
member(obj222, '@id', 'jsonschema:maxItems') .
member(obj222, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj216, 'maxItems', obj222) .
member(obj223, '@id', 'jsonschema:minItems') .
member(obj223, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj216, 'minItems', obj223) .
member(obj224, '@id', 'jsonschema:items') .
member(obj224, '@type', '@id') .
member(obj216, 'items', obj224) .
member(obj225, '@id', 'jsonschema:required') .
member(obj225, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj225, '@container', '@set') .
member(obj216, 'required', obj225) .
member(obj226, '@id', 'jsonschema:enum') .
member(obj226, '@type', '@id') .
member(obj226, '@container', '@set') .
member(obj216, 'enum', obj226) .
member(obj227, '@id', 'jsonschema:const') .
member(obj216, 'const', obj227) .
member(obj228, '@id', 'jsonschema:unit') .
member(obj216, 'unit', obj228) .
member(obj229, '@id', 'jsonschema:oneOf') .
member(obj229, '@container', '@set') .
member(obj216, 'oneOf', obj229) .
member(obj230, '@id', 'rdf:type') .
member(obj230, '@type', '@vocab') .
member(obj216, 'type', obj230) .
member(obj216, 'object', 'jsonschema:ObjectSchema') .
member(obj216, 'array', 'jsonschema:ArraySchema') .
member(obj216, 'boolean', 'jsonschema:BooleanSchema') .
member(obj216, 'string', 'jsonschema:StringSchema') .
member(obj216, 'number', 'jsonschema:NumberSchema') .
member(obj216, 'integer', 'jsonschema:IntegerSchema') .
member(obj216, 'null', 'jsonschema:NullSchema') .
member(obj231, '@id', 'jsonschema:properties') .
member(obj231, '@type', '@id') .
member(obj231, '@container', '@index') .
member(obj216, 'properties', obj231) .
member(obj215, '@context', obj216) .
member(obj86, 'data', obj215) .
member(obj232, '@id', 'td:hasCancellationSchema') .
member(obj232, '@type', '@id') .
member(obj233, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj233, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj233, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj233, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj233, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj234, '@id', 'jsonschema:DataSchema') .
member(obj233, 'DataSchema', obj234) .
member(obj235, '@id', 'jsonschema:readOnly') .
member(obj235, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj233, 'readOnly', obj235) .
member(obj236, '@id', 'jsonschema:writeOnly') .
member(obj236, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj233, 'writeOnly', obj236) .
member(obj237, '@id', 'jsonschema:maximum') .
member(obj233, 'maximum', obj237) .
member(obj238, '@id', 'jsonschema:minimum') .
member(obj233, 'minimum', obj238) .
member(obj239, '@id', 'jsonschema:maxItems') .
member(obj239, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj233, 'maxItems', obj239) .
member(obj240, '@id', 'jsonschema:minItems') .
member(obj240, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj233, 'minItems', obj240) .
member(obj241, '@id', 'jsonschema:items') .
member(obj241, '@type', '@id') .
member(obj233, 'items', obj241) .
member(obj242, '@id', 'jsonschema:required') .
member(obj242, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj242, '@container', '@set') .
member(obj233, 'required', obj242) .
member(obj243, '@id', 'jsonschema:enum') .
member(obj243, '@type', '@id') .
member(obj243, '@container', '@set') .
member(obj233, 'enum', obj243) .
member(obj244, '@id', 'jsonschema:const') .
member(obj233, 'const', obj244) .
member(obj245, '@id', 'jsonschema:unit') .
member(obj233, 'unit', obj245) .
member(obj246, '@id', 'jsonschema:oneOf') .
member(obj246, '@container', '@set') .
member(obj233, 'oneOf', obj246) .
member(obj247, '@id', 'rdf:type') .
member(obj247, '@type', '@vocab') .
member(obj233, 'type', obj247) .
member(obj233, 'object', 'jsonschema:ObjectSchema') .
member(obj233, 'array', 'jsonschema:ArraySchema') .
member(obj233, 'boolean', 'jsonschema:BooleanSchema') .
member(obj233, 'string', 'jsonschema:StringSchema') .
member(obj233, 'number', 'jsonschema:NumberSchema') .
member(obj233, 'integer', 'jsonschema:IntegerSchema') .
member(obj233, 'null', 'jsonschema:NullSchema') .
member(obj248, '@id', 'jsonschema:properties') .
member(obj248, '@type', '@id') .
member(obj248, '@container', '@index') .
member(obj233, 'properties', obj248) .
member(obj232, '@context', obj233) .
member(obj86, 'cancellation', obj232) .
member(obj249, '@id', 'td:description') .
member(obj86, 'description', obj249) .
member(obj250, '@id', 'td:descriptions') .
member(obj250, '@container', '@language') .
member(obj86, 'descriptions', obj250) .
member(obj251, '@id', 'td:title') .
member(obj86, 'title', obj251) .
member(obj252, '@id', 'td:supportContact') .
member(obj86, 'support', obj252) .
member(obj253, '@id', 'td:defaultUnit') .
member(obj86, 'unit', obj253) .
member(obj86, '@version', 1.1) .
member(obj85, '@context', obj86) .
member(obj85, 'id', 'urn:dev:ops:32473-WoTLamp-1234') .
member(obj85, 'title', 'MyLampThing') .
member(obj255, 'scheme', 'basic') .
member(obj255, 'in', 'header') .
member(obj254, 'basic_sc', obj255) .
member(obj85, 'securityDefinitions', obj254) .
member(obj256, 0, 'basic_sc') .
member(obj85, 'security', obj256) .
member(obj258, 'type', 'string') .
member(obj260, 'href', 'https://mylamp.example.com/status') .
member(obj259, 0, obj260) .
member(obj258, 'forms', obj259) .
member(obj257, 'status', obj258) .
member(obj85, 'properties', obj257) .
member(obj264, 'href', 'https://mylamp.example.com/toggle') .
member(obj263, 0, obj264) .
member(obj262, 'forms', obj263) .
member(obj261, 'toggle', obj262) .
member(obj85, 'actions', obj261) .
member(obj267, 'type', 'string') .
member(obj266, 'data', obj267) .
member(obj269, 'href', 'https://mylamp.example.com/oh') .
member(obj269, 'subprotocol', 'longpoll') .
member(obj268, 0, obj269) .
member(obj266, 'forms', obj268) .
member(obj265, 'overheating', obj266) .
member(obj85, 'events', obj265) .
root('td.jsonld', obj85) .
member(obj271, 'Restaurant', 'http://schema.org/Restaurant') .
member(obj271, 'Brewery', 'http://schema.org/Brewery') .
member(obj270, '@context', obj271) .
member(obj270, '@id', 'http://example.org/places#BrewEats') .
member(obj272, 0, 'Restaurant') .
member(obj272, 1, 'Brewery') .
member(obj270, '@type', obj272) .
root('type-array-ctx.jsonld', obj270) .
member(obj273, '@id', 'http://example.org/places#BrewEats') .
member(obj274, 0, 'http://schema.org/Restaurant') .
member(obj274, 1, 'http://schema.org/Brewery') .
member(obj273, '@type', obj274) .
root('type-array.jsonld', obj273) .
member(obj276, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj277, '@id', 'http://xmlns.com/foaf/0.1/age') .
member(obj277, '@type', 'xsd:integer') .
member(obj276, 'foaf:age', obj277) .
member(obj278, '@type', '@id') .
member(obj276, 'http://xmlns.com/foaf/0.1/homepage', obj278) .
member(obj275, '@context', obj276) .
member(obj275, 'foaf:name', 'John Smith') .
member(obj275, 'foaf:age', '41') .
member(obj279, 0, 'http://personal.example.org/') .
member(obj279, 1, 'http://work.example.com/jsmith/') .
member(obj275, 'http://xmlns.com/foaf/0.1/homepage', obj279) .
root('type-coercion-ctx.jsonld', obj275) .
member(obj281, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj281, 'name', 'http://xmlns.com/foaf/0.1/name') .
member(obj282, '@id', 'http://xmlns.com/foaf/0.1/age') .
member(obj282, '@type', 'xsd:integer') .
member(obj281, 'age', obj282) .
member(obj283, '@id', 'http://xmlns.com/foaf/0.1/homepage') .
member(obj283, '@type', '@id') .
member(obj281, 'homepage', obj283) .
member(obj280, '@context', obj281) .
member(obj280, '@id', 'http://example.com/people#john') .
member(obj280, 'name', 'John Smith') .
member(obj280, 'age', '41') .
member(obj284, 0, 'http://personal.example.org/') .
member(obj284, 1, 'http://work.example.com/jsmith/') .
member(obj280, 'homepage', obj284) .
root('type-coercion.jsonld', obj280) .
member(obj287, '@id', 'http://purl.org/dc/terms/modified') .
member(obj287, '@type', 'http://www.w3.org/2001/XMLSchema#dateTime') .
member(obj286, 'modified', obj287) .
member(obj285, '@context', obj286) .
member(obj285, '@id', 'http://example.com/docs/1') .
member(obj285, 'modified', '2010-05-29T14:17:39+02:00') .
root('type-ctx.jsonld', obj285) .
member(obj288, '@id', 'http://example.org/places#BrewEats') .
member(obj288, '@type', 'http://schema.org/Restaurant') .
root('type.jsonld', obj288) .
member(obj290, '@vocab', 'http://schema.org/') .
member(obj290, 'databaseId', obj291) .
member(obj289, '@context', obj290) .
member(obj289, '@id', 'http://example.org/places#BrewEats') .
member(obj289, '@type', 'Restaurant') .
member(obj289, 'name', 'Brew Eats') .
member(obj289, 'databaseId', '23987520') .
root('vocab-null.jsonld', obj289) .
member(obj293, '@vocab', 'http://schema.org/') .
member(obj292, '@context', obj293) .
member(obj292, '@id', 'http://example.org/places#BrewEats') .
member(obj292, '@type', 'Restaurant') .
member(obj292, 'name', 'Brew Eats') .
root('vocab.jsonld', obj292) .
