member(obj1, 'url', '@id') .
member(obj1, 'a', '@type') .
member(obj1, 'name', 'http://xmlns.com/foaf/0.1/name') .
member(obj0, '@context', obj1) .
member(obj0, 'url', 'http://example.com/about#gregg') .
member(obj0, 'a', 'http://xmlns.com/foaf/0.1/Person') .
member(obj0, 'name', 'Gregg Kellogg') .
root('alias.jsonld', obj0) .
member(obj3, '@base', 'http://example.com/document.jsonld') .
member(obj2, '@context', obj3) .
member(obj2, '@id', '') .
member(obj2, 'label', 'Just a simple document') .
root('base-uri-ctx.jsonld', obj2) .
member(obj5, 'label', 'http://www.w3.org/2000/01/rdf-schema#label') .
member(obj4, '@context', obj5) .
member(obj4, '@id', '') .
member(obj4, 'label', 'Just a simple document') .
root('base-uri.jsonld', obj4) .
member(obj8, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj8, 'name', 'foaf:name') .
member(obj8, 'homepage', 'foaf:homepage') .
member(obj7, 0, obj8) .
member(obj9, 'pic', 'http://xmlns.com/foaf/0.1/depiction') .
member(obj7, 1, obj9) .
member(obj6, '@context', obj7) .
member(obj6, 'name', 'Manu Sporny') .
member(obj6, 'homepage', 'http://manu.sporny.org/') .
member(obj6, 'pic', 'http://twitter.com/account/profile_image/manusporny') .
root('combined-ctx.jsonld', obj6) .
member(obj11, 'name', 'http://schema.org/name') .
member(obj12, '@id', 'http://schema.org/image') .
member(obj12, '@type', '@id') .
member(obj11, 'image', obj12) .
member(obj13, '@id', 'http://schema.org/url') .
member(obj13, '@type', '@id') .
member(obj11, 'homepage', obj13) .
member(obj10, '@context', obj11) .
member(obj10, 'name', 'Manu Sporny') .
member(obj10, 'homepage', 'http://manu.sporny.org/') .
member(obj10, 'image', 'http://manu.sporny.org/images/manu.png') .
root('ctx-inline.jsonld', obj10) .
member(obj14, '@context', 'http://json-ld.org/contexts/person.jsonld') .
member(obj14, 'name', 'Manu Sporny') .
member(obj14, 'homepage', 'http://manu.sporny.org/') .
member(obj14, 'image', 'http://manu.sporny.org/images/manu.png') .
root('ctx-remote.jsonld', obj14) .
member(obj16, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj16, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj17, '@type', '@id') .
member(obj16, 'foaf:homepage', obj17) .
member(obj18, '@id', 'foaf:depiction') .
member(obj18, '@type', '@id') .
member(obj16, 'picture', obj18) .
member(obj15, '@context', obj16) .
member(obj15, '@id', 'http://me.markus-lanthaler.com/') .
member(obj15, '@type', 'foaf:Person') .
member(obj15, 'foaf:name', 'Markus Lanthaler') .
member(obj15, 'foaf:homepage', 'http://www.markus-lanthaler.com/') .
member(obj15, 'picture', 'http://twitter.com/account/profile_image/markuslanthaler') .
root('curie-ctx.jsonld', obj15) .
member(obj20, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj19, '@context', obj20) .
member(obj19, '@type', 'foaf:Person') .
member(obj19, 'foaf:name', 'Dave Longley') .
root('curie.jsonld', obj19) .
member(obj22, 'Person', 'http://xmlns.com/foaf/0.1/Person') .
member(obj22, 'name', 'http://xmlns.com/foaf/0.1/name') .
member(obj22, 'knows', 'http://xmlns.com/foaf/0.1/knows') .
member(obj21, '@context', obj22) .
member(obj24, '@id', 'http://manu.sporny.org/about#manu') .
member(obj24, '@type', 'foaf:Person') .
member(obj24, 'name', 'Manu Sporny') .
member(obj24, 'knows', 'http://greggkellogg.net/foaf#me') .
member(obj23, 0, obj24) .
member(obj25, '@id', 'http://greggkellogg.net/foaf#me') .
member(obj25, '@type', 'foaf:Person') .
member(obj25, 'name', 'Gregg Kellogg') .
member(obj25, 'knows', 'http://manu.sporny.org/about#manu') .
member(obj23, 1, obj25) .
member(obj21, '@graph', obj23) .
root('default-graph.jsonld', obj21) .
member(obj27, 'name', 'http://schema.org/name') .
member(obj27, 'Person', 'http://schema.org/Person') .
member(obj27, 'knows', 'http://xmlns.com/foaf/0.1/knows') .
member(obj26, '@context', obj27) .
member(obj26, 'name', 'Manu Sporny') .
member(obj28, '@type', 'Person') .
member(obj28, 'name', 'Gregg Kellogg') .
member(obj26, 'knows', obj28) .
root('embedding.jsonld', obj26) .
member(obj30, 'schema', 'http://schema.org/') .
member(obj30, 'name', 'schema:name') .
member(obj30, 'body', 'schema:articleBody') .
member(obj30, 'words', 'schema:wordCount') .
member(obj31, '@id', 'schema:blogPost') .
member(obj31, '@container', '@index') .
member(obj30, 'post', obj31) .
member(obj29, '@context', obj30) .
member(obj29, '@id', 'http://example.com/') .
member(obj29, '@type', 'schema:Blog') .
member(obj29, 'name', 'World Financial News') .
member(obj33, '@id', 'http://example.com/posts/1/en') .
member(obj33, 'body', 'World commodities were up today with heavy trading of crude oil...') .
member(obj33, 'words', 1539) .
member(obj32, 'en', obj33) .
member(obj34, '@id', 'http://example.com/posts/1/de') .
member(obj34, 'body', 'Die Werte an Warenbörsen stiegen im Sog eines starken Handels von Rohöl...') .
member(obj34, 'words', 1204) .
member(obj32, 'de', obj34) .
member(obj29, 'post', obj32) .
root('index.jsonld', obj29) .
member(obj35, 'http://schema.org/name', 'Manu Sporny') .
member(obj36, '@id', 'http://manu.sporny.org/') .
member(obj35, 'http://schema.org/url', obj36) .
member(obj37, '@id', 'http://manu.sporny.org/images/manu.png') .
member(obj35, 'http://schema.org/image', obj37) .
root('intro.jsonld', obj35) .
member(obj39, 'name', 'http://schema.org/name') .
member(obj38, '@context', obj39) .
member(obj38, 'name', 'Manu Sporny') .
member(obj38, 'status', 'trollin') .
root('iris-ignored.jsonld', obj38) .
member(obj42, '@id', 'http://xmlns.com/foaf/0.1/nick') .
member(obj42, '@container', '@list') .
member(obj41, 'nick', obj42) .
member(obj40, '@context', obj41) .
member(obj40, '@id', 'http://example.org/people#joebob') .
member(obj43, 0, 'joe') .
member(obj43, 1, 'bob') .
member(obj43, 2, 'jaybee') .
member(obj40, 'nick', obj43) .
root('list-ctx.jsonld', obj40) .
member(obj45, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj44, '@context', obj45) .
member(obj44, '@id', 'http://example.org/people#joebob') .
member(obj47, 0, 'joe') .
member(obj47, 1, 'bob') .
member(obj47, 2, 'jaybee') .
member(obj46, '@list', obj47) .
member(obj44, 'foaf:nick', obj46) .
root('list.jsonld', obj44) .
member(obj50, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj50, 'name', 'foaf:name') .
member(obj50, 'homepage', 'foaf:homepage') .
member(obj50, 'depiction', 'foaf:depiction') .
member(obj49, '@context', obj50) .
member(obj49, 'name', 'Manu Sporny') .
member(obj49, 'homepage', 'http://manu.sporny.org/') .
member(obj49, 'depiction', 'http://twitter.com/account/profile_image/manusporny') .
member(obj48, 0, obj49) .
member(obj52, 'schema', 'http://schema.org/') .
member(obj52, 'name', 'schema:name') .
member(obj52, 'description', 'schema:description') .
member(obj52, 'geo', 'schema:geo') .
member(obj52, 'latitude', 'schema:latitude') .
member(obj52, 'longitude', 'schema:longitude') .
member(obj51, '@context', obj52) .
member(obj51, 'name', 'The Empire State Building') .
member(obj51, 'description', 'The Empire State Building is a 102-story landmark in New York City.') .
member(obj53, 'latitude', '40.75') .
member(obj53, 'longitude', '73.98') .
member(obj51, 'geo', obj53) .
member(obj48, 1, obj51) .
root('multi-ctx.jsonld', obj48) .
member(obj55, 'dc', 'http://purl.org/dc/terms/') .
member(obj54, '@context', obj55) .
member(obj54, '@id', 'http://example.org/articles/8') .
member(obj57, '@value', 'Das Kapital') .
member(obj57, '@language', 'de') .
member(obj56, 0, obj57) .
member(obj58, '@value', 'Capital') .
member(obj58, '@language', 'en') .
member(obj56, 1, obj58) .
member(obj54, 'dc:title', obj56) .
root('multi-expanded-values.jsonld', obj54) .
member(obj60, 'nick', 'http://xmlns.com/foaf/0.1/nick') .
member(obj59, '@context', obj60) .
member(obj59, '@id', 'http://example.org/people#joebob') .
member(obj61, 0, 'joe') .
member(obj61, 1, 'bob') .
member(obj61, 2, 'JB') .
member(obj59, 'nick', obj61) .
root('multi-values.jsonld', obj59) .
member(obj64, '@id', 'http://www.w3.org/ns/prov#generatedAtTime') .
member(obj64, '@type', 'http://www.w3.org/2001/XMLSchema#date') .
member(obj63, 'generatedAt', obj64) .
member(obj63, 'Person', 'http://xmlns.com/foaf/0.1/Person') .
member(obj63, 'name', 'http://xmlns.com/foaf/0.1/name') .
member(obj63, 'knows', 'http://xmlns.com/foaf/0.1/knows') .
member(obj62, '@context', obj63) .
member(obj62, '@id', 'http://example.org/graphs/73') .
member(obj62, 'generatedAt', '2012-04-09') .
member(obj66, '@id', 'http://manu.sporny.org/about#manu') .
member(obj66, '@type', 'Person') .
member(obj66, 'name', 'Manu Sporny') .
member(obj66, 'knows', 'http://greggkellogg.net/foaf#me') .
member(obj65, 0, obj66) .
member(obj67, '@id', 'http://greggkellogg.net/foaf#me') .
member(obj67, '@type', 'Person') .
member(obj67, 'name', 'Gregg Kellogg') .
member(obj67, 'knows', 'http://manu.sporny.org/about#manu') .
member(obj65, 1, obj67) .
member(obj62, '@graph', obj65) .
root('named-graph.jsonld', obj62) .
member(obj69, 'name', 'http://schema.org/name') .
member(obj68, '@context', obj69) .
member(obj68, '@id', 'http://me.markus-lanthaler.com/') .
member(obj68, 'name', 'Markus Lanthaler') .
root('node-id.jsonld', obj68) .
member(obj71, 'Person', 'http://schema.org/Person') .
member(obj71, 'name', 'http://schema.org/name') .
member(obj71, 'jobTitle', 'http://schema.org/jobTitle') .
member(obj71, 'telephone', 'http://schema.org/telephone') .
member(obj72, '@id', 'http://schema.org/url') .
member(obj72, '@type', '@id') .
member(obj71, 'url', obj72) .
member(obj70, '@context', obj71) .
member(obj70, '@type', 'Person') .
member(obj70, 'name', 'Jane Doe') .
member(obj70, 'jobTitle', 'Professor') .
member(obj70, 'telephone', '(425) 123-4567') .
member(obj70, 'url', 'http://www.janedoe.com') .
root('person.jsonld', obj70) .
member(obj74, 'name', 'http://example.com/vocab#name') .
member(obj75, '@reverse', 'http://example.com/vocab#parent') .
member(obj74, 'children', obj75) .
member(obj73, '@context', obj74) .
member(obj73, '@id', '#homer') .
member(obj73, 'name', 'Homer') .
member(obj77, '@id', '#bart') .
member(obj77, 'name', 'Bart') .
member(obj76, 0, obj77) .
member(obj78, '@id', '#lisa') .
member(obj78, 'name', 'Lisa') .
member(obj76, 1, obj78) .
member(obj73, 'children', obj76) .
root('reverse-ctx.jsonld', obj73) .
member(obj79, '@id', '#homer') .
member(obj79, 'http://example.com/vocab#name', 'Homer') .
member(obj82, '@id', '#bart') .
member(obj82, 'http://example.com/vocab#name', 'Bart') .
member(obj81, 0, obj82) .
member(obj83, '@id', '#lisa') .
member(obj83, 'http://example.com/vocab#name', 'Lisa') .
member(obj81, 1, obj83) .
member(obj80, 'http://example.com/vocab#parent', obj81) .
member(obj79, '@reverse', obj80) .
root('reverse.jsonld', obj79) .
member(obj85, 'name', 'http://example.com/person#name') .
member(obj85, 'details', 'http://example.com/person#details') .
member(obj84, '@context', obj85) .
member(obj84, 'name', 'Markus Lanthaler') .
member(obj87, 'name', 'http://example.com/organization#name') .
member(obj86, '@context', obj87) .
member(obj86, 'name', 'Graz University of Technology') .
member(obj84, 'details', obj86) .
root('scoped-ctx.jsonld', obj84) .
member(obj89, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj89, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj89, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj89, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj89, 'rdfs', 'http://www.w3.org/2000/01/rdf-schema#') .
member(obj89, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj90, '@id', 'http://purl.org/dc/terms/license') .
member(obj89, 'license', obj90) .
member(obj89, 'id', '@id') .
member(obj91, '@id', 'td:hasPropertyAffordance') .
member(obj91, '@type', '@id') .
member(obj91, '@container', '@index') .
member(obj92, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj92, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj92, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj92, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj92, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj93, '@id', 'jsonschema:DataSchema') .
member(obj92, 'DataSchema', obj93) .
member(obj94, '@id', 'jsonschema:readOnly') .
member(obj94, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj92, 'readOnly', obj94) .
member(obj95, '@id', 'jsonschema:writeOnly') .
member(obj95, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj92, 'writeOnly', obj95) .
member(obj96, '@id', 'jsonschema:maximum') .
member(obj92, 'maximum', obj96) .
member(obj97, '@id', 'jsonschema:minimum') .
member(obj92, 'minimum', obj97) .
member(obj98, '@id', 'jsonschema:maxItems') .
member(obj98, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj92, 'maxItems', obj98) .
member(obj99, '@id', 'jsonschema:minItems') .
member(obj99, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj92, 'minItems', obj99) .
member(obj100, '@id', 'jsonschema:items') .
member(obj100, '@type', '@id') .
member(obj92, 'items', obj100) .
member(obj101, '@id', 'jsonschema:required') .
member(obj101, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj101, '@container', '@set') .
member(obj92, 'required', obj101) .
member(obj102, '@id', 'jsonschema:enum') .
member(obj102, '@type', '@id') .
member(obj102, '@container', '@set') .
member(obj92, 'enum', obj102) .
member(obj103, '@id', 'jsonschema:const') .
member(obj92, 'const', obj103) .
member(obj104, '@id', 'jsonschema:unit') .
member(obj92, 'unit', obj104) .
member(obj105, '@id', 'jsonschema:oneOf') .
member(obj105, '@container', '@set') .
member(obj92, 'oneOf', obj105) .
member(obj106, '@id', 'rdf:type') .
member(obj106, '@type', '@vocab') .
member(obj92, 'type', obj106) .
member(obj92, 'object', 'jsonschema:ObjectSchema') .
member(obj92, 'array', 'jsonschema:ArraySchema') .
member(obj92, 'boolean', 'jsonschema:BooleanSchema') .
member(obj92, 'string', 'jsonschema:StringSchema') .
member(obj92, 'number', 'jsonschema:NumberSchema') .
member(obj92, 'integer', 'jsonschema:IntegerSchema') .
member(obj92, 'null', 'jsonschema:NullSchema') .
member(obj107, '@id', 'jsonschema:properties') .
member(obj107, '@type', '@id') .
member(obj107, '@container', '@index') .
member(obj92, 'properties', obj107) .
member(obj91, '@context', obj92) .
member(obj89, 'properties', obj91) .
member(obj108, '@id', 'td:hasActionAffordance') .
member(obj108, '@type', '@id') .
member(obj108, '@container', '@index') .
member(obj89, 'actions', obj108) .
member(obj109, '@id', 'td:hasEventAffordance') .
member(obj109, '@type', '@id') .
member(obj109, '@container', '@index') .
member(obj89, 'events', obj109) .
member(obj110, '@id', 'td:hasSecurityConfiguration') .
member(obj110, '@type', '@id') .
member(obj110, '@container', '@set') .
member(obj111, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj111, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj111, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj111, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj111, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj112, '@id', 'wotsec:in') .
member(obj111, 'in', obj112) .
member(obj113, '@id', 'wotsec:authorization') .
member(obj111, 'authorization', obj113) .
member(obj114, '@id', 'wotsec:token') .
member(obj111, 'token', obj114) .
member(obj115, '@id', 'wotsec:refresh') .
member(obj111, 'refresh', obj115) .
member(obj116, '@id', 'wotsec:proxy') .
member(obj111, 'proxy', obj116) .
member(obj117, '@id', 'wotsec:scopes') .
member(obj117, '@container', '@set') .
member(obj111, 'scopes', obj117) .
member(obj118, '@id', 'wotsec:flow') .
member(obj111, 'flow', obj118) .
member(obj119, '@id', 'wotsec:qop') .
member(obj111, 'qop', obj119) .
member(obj120, '@id', 'wotsec:alg') .
member(obj111, 'alg', obj120) .
member(obj121, '@id', 'wotsec:format') .
member(obj111, 'format', obj121) .
member(obj122, '@id', 'wotsec:identity') .
member(obj111, 'identity', obj122) .
member(obj123, '@id', 'rdf:type') .
member(obj123, '@type', '@vocab') .
member(obj111, 'scheme', obj123) .
member(obj111, 'nosec', 'wotsec:NoSecurityScheme') .
member(obj111, 'basic', 'wotsec:BasicSecurityScheme') .
member(obj111, 'digest', 'wotsec:DigestSecurityScheme') .
member(obj111, 'apikey', 'wotsec:APIKeySecurityScheme') .
member(obj111, 'bearer', 'wotsec:BearerSecurityScheme') .
member(obj111, 'cert', 'wotsec:CertSecurityScheme') .
member(obj111, 'psk', 'wotsec:PSKSecurityScheme') .
member(obj111, 'public', 'wotsec:PublicSecurityScheme') .
member(obj111, 'pop', 'wotsec:PoPSecurityScheme') .
member(obj111, 'oauth2', 'wotsec:OAuth2SecurityScheme') .
member(obj110, '@context', obj111) .
member(obj89, 'security', obj110) .
member(obj124, '@id', 'td:securityDefinitions') .
member(obj124, '@type', '@id') .
member(obj124, '@container', '@index') .
member(obj89, 'securityDefinitions', obj124) .
member(obj125, '@id', 'td:Thing') .
member(obj89, 'Thing', obj125) .
member(obj126, '@id', 'td:EventAffordance') .
member(obj89, 'EventAffordance', obj126) .
member(obj127, '@id', 'td:baseUri') .
member(obj127, '@type', 'xsd:anyURI') .
member(obj89, 'base', obj127) .
member(obj128, '@id', 'td:name') .
member(obj89, 'name', obj128) .
member(obj129, '@id', 'td:created') .
member(obj89, 'created', obj129) .
member(obj130, '@id', 'td:modified') .
member(obj89, 'modified', obj130) .
member(obj131, '@id', 'td:isObservable') .
member(obj131, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj89, 'observable', obj131) .
member(obj132, '@id', 'td:VersionInfo') .
member(obj89, 'VersionInfo', obj132) .
member(obj133, '@id', 'td:PropertyAffordance') .
member(obj89, 'PropertyAffordance', obj133) .
member(obj134, '@id', 'td:hasForm') .
member(obj134, '@type', '@id') .
member(obj134, '@container', '@set') .
member(obj135, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj135, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj135, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj135, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj135, 'rdfs', 'http://www.w3.org/2000/01/rdf-schema#') .
member(obj135, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj136, '@id', 'hyperm:Link') .
member(obj135, 'Link', obj136) .
member(obj137, '@id', 'hyperm:Form') .
member(obj135, 'Form', obj137) .
member(obj138, '@id', 'hyperm:forOperationType') .
member(obj138, '@container', '@set') .
member(obj135, 'op', obj138) .
member(obj139, '@id', 'hyperm:forSubProtocol') .
member(obj135, 'subprotocol', obj139) .
member(obj140, '@id', 'hyperm:forContentType') .
member(obj140, '@type', 'xsd:string') .
member(obj135, 'contentType', obj140) .
member(obj141, '@id', 'hyperm:forContentCoding') .
member(obj141, '@type', 'xsd:string') .
member(obj135, 'contentCoding', obj141) .
member(obj142, '@id', 'hyperm:hasAnchor') .
member(obj135, 'anchor', obj142) .
member(obj143, '@id', 'hyperm:hasTarget') .
member(obj135, 'href', obj143) .
member(obj144, '@id', 'hyperm:hasRelationType') .
member(obj135, 'rel', obj144) .
member(obj145, '@id', 'hyperm:hintsAtMediaType') .
member(obj135, 'type', obj145) .
member(obj146, '@id', 'hyperm:returns') .
member(obj135, 'response', obj146) .
member(obj134, '@context', obj135) .
member(obj89, 'forms', obj134) .
member(obj147, '@id', 'td:versionInfo') .
member(obj147, '@type', '@id') .
member(obj89, 'version', obj147) .
member(obj148, '@id', 'td:hasLink') .
member(obj148, '@type', '@id') .
member(obj148, '@container', '@set') .
member(obj149, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj149, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj149, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj149, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj149, 'rdfs', 'http://www.w3.org/2000/01/rdf-schema#') .
member(obj149, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj150, '@id', 'hyperm:Link') .
member(obj149, 'Link', obj150) .
member(obj151, '@id', 'hyperm:Form') .
member(obj149, 'Form', obj151) .
member(obj152, '@id', 'hyperm:forOperationType') .
member(obj152, '@container', '@set') .
member(obj149, 'op', obj152) .
member(obj153, '@id', 'hyperm:forSubProtocol') .
member(obj149, 'subprotocol', obj153) .
member(obj154, '@id', 'hyperm:forContentType') .
member(obj154, '@type', 'xsd:string') .
member(obj149, 'contentType', obj154) .
member(obj155, '@id', 'hyperm:forContentCoding') .
member(obj155, '@type', 'xsd:string') .
member(obj149, 'contentCoding', obj155) .
member(obj156, '@id', 'hyperm:hasAnchor') .
member(obj149, 'anchor', obj156) .
member(obj157, '@id', 'hyperm:hasTarget') .
member(obj149, 'href', obj157) .
member(obj158, '@id', 'hyperm:hasRelationType') .
member(obj149, 'rel', obj158) .
member(obj159, '@id', 'hyperm:hintsAtMediaType') .
member(obj149, 'type', obj159) .
member(obj160, '@id', 'hyperm:returns') .
member(obj149, 'response', obj160) .
member(obj148, '@context', obj149) .
member(obj89, 'links', obj148) .
member(obj161, '@id', 'td:hasUriTemplateVariable') .
member(obj161, '@container', '@index') .
member(obj89, 'uriVariables', obj161) .
member(obj162, '@id', 'td:isSafe') .
member(obj89, 'safe', obj162) .
member(obj163, '@id', 'td:isIdempotent') .
member(obj89, 'idempotent', obj163) .
member(obj164, '@id', 'td:instance') .
member(obj89, 'instance', obj164) .
member(obj165, '@id', 'td:InteractionAffordance') .
member(obj89, 'InteractionAffordance', obj165) .
member(obj166, '@id', 'td:ActionAffordance') .
member(obj89, 'ActionAffordance', obj166) .
member(obj167, '@id', 'td:hasInputSchema') .
member(obj167, '@type', '@id') .
member(obj168, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj168, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj168, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj168, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj168, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj169, '@id', 'jsonschema:DataSchema') .
member(obj168, 'DataSchema', obj169) .
member(obj170, '@id', 'jsonschema:readOnly') .
member(obj170, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj168, 'readOnly', obj170) .
member(obj171, '@id', 'jsonschema:writeOnly') .
member(obj171, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj168, 'writeOnly', obj171) .
member(obj172, '@id', 'jsonschema:maximum') .
member(obj168, 'maximum', obj172) .
member(obj173, '@id', 'jsonschema:minimum') .
member(obj168, 'minimum', obj173) .
member(obj174, '@id', 'jsonschema:maxItems') .
member(obj174, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj168, 'maxItems', obj174) .
member(obj175, '@id', 'jsonschema:minItems') .
member(obj175, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj168, 'minItems', obj175) .
member(obj176, '@id', 'jsonschema:items') .
member(obj176, '@type', '@id') .
member(obj168, 'items', obj176) .
member(obj177, '@id', 'jsonschema:required') .
member(obj177, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj177, '@container', '@set') .
member(obj168, 'required', obj177) .
member(obj178, '@id', 'jsonschema:enum') .
member(obj178, '@type', '@id') .
member(obj178, '@container', '@set') .
member(obj168, 'enum', obj178) .
member(obj179, '@id', 'jsonschema:const') .
member(obj168, 'const', obj179) .
member(obj180, '@id', 'jsonschema:unit') .
member(obj168, 'unit', obj180) .
member(obj181, '@id', 'jsonschema:oneOf') .
member(obj181, '@container', '@set') .
member(obj168, 'oneOf', obj181) .
member(obj182, '@id', 'rdf:type') .
member(obj182, '@type', '@vocab') .
member(obj168, 'type', obj182) .
member(obj168, 'object', 'jsonschema:ObjectSchema') .
member(obj168, 'array', 'jsonschema:ArraySchema') .
member(obj168, 'boolean', 'jsonschema:BooleanSchema') .
member(obj168, 'string', 'jsonschema:StringSchema') .
member(obj168, 'number', 'jsonschema:NumberSchema') .
member(obj168, 'integer', 'jsonschema:IntegerSchema') .
member(obj168, 'null', 'jsonschema:NullSchema') .
member(obj183, '@id', 'jsonschema:properties') .
member(obj183, '@type', '@id') .
member(obj183, '@container', '@index') .
member(obj168, 'properties', obj183) .
member(obj167, '@context', obj168) .
member(obj89, 'input', obj167) .
member(obj184, '@id', 'td:hasOutputSchema') .
member(obj184, '@type', '@id') .
member(obj185, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj185, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj185, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj185, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj185, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj186, '@id', 'jsonschema:DataSchema') .
member(obj185, 'DataSchema', obj186) .
member(obj187, '@id', 'jsonschema:readOnly') .
member(obj187, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj185, 'readOnly', obj187) .
member(obj188, '@id', 'jsonschema:writeOnly') .
member(obj188, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj185, 'writeOnly', obj188) .
member(obj189, '@id', 'jsonschema:maximum') .
member(obj185, 'maximum', obj189) .
member(obj190, '@id', 'jsonschema:minimum') .
member(obj185, 'minimum', obj190) .
member(obj191, '@id', 'jsonschema:maxItems') .
member(obj191, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj185, 'maxItems', obj191) .
member(obj192, '@id', 'jsonschema:minItems') .
member(obj192, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj185, 'minItems', obj192) .
member(obj193, '@id', 'jsonschema:items') .
member(obj193, '@type', '@id') .
member(obj185, 'items', obj193) .
member(obj194, '@id', 'jsonschema:required') .
member(obj194, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj194, '@container', '@set') .
member(obj185, 'required', obj194) .
member(obj195, '@id', 'jsonschema:enum') .
member(obj195, '@type', '@id') .
member(obj195, '@container', '@set') .
member(obj185, 'enum', obj195) .
member(obj196, '@id', 'jsonschema:const') .
member(obj185, 'const', obj196) .
member(obj197, '@id', 'jsonschema:unit') .
member(obj185, 'unit', obj197) .
member(obj198, '@id', 'jsonschema:oneOf') .
member(obj198, '@container', '@set') .
member(obj185, 'oneOf', obj198) .
member(obj199, '@id', 'rdf:type') .
member(obj199, '@type', '@vocab') .
member(obj185, 'type', obj199) .
member(obj185, 'object', 'jsonschema:ObjectSchema') .
member(obj185, 'array', 'jsonschema:ArraySchema') .
member(obj185, 'boolean', 'jsonschema:BooleanSchema') .
member(obj185, 'string', 'jsonschema:StringSchema') .
member(obj185, 'number', 'jsonschema:NumberSchema') .
member(obj185, 'integer', 'jsonschema:IntegerSchema') .
member(obj185, 'null', 'jsonschema:NullSchema') .
member(obj200, '@id', 'jsonschema:properties') .
member(obj200, '@type', '@id') .
member(obj200, '@container', '@index') .
member(obj185, 'properties', obj200) .
member(obj184, '@context', obj185) .
member(obj89, 'output', obj184) .
member(obj201, '@id', 'td:hasSubscriptionSchema') .
member(obj201, '@type', '@id') .
member(obj202, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj202, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj202, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj202, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj202, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj203, '@id', 'jsonschema:DataSchema') .
member(obj202, 'DataSchema', obj203) .
member(obj204, '@id', 'jsonschema:readOnly') .
member(obj204, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj202, 'readOnly', obj204) .
member(obj205, '@id', 'jsonschema:writeOnly') .
member(obj205, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj202, 'writeOnly', obj205) .
member(obj206, '@id', 'jsonschema:maximum') .
member(obj202, 'maximum', obj206) .
member(obj207, '@id', 'jsonschema:minimum') .
member(obj202, 'minimum', obj207) .
member(obj208, '@id', 'jsonschema:maxItems') .
member(obj208, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj202, 'maxItems', obj208) .
member(obj209, '@id', 'jsonschema:minItems') .
member(obj209, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj202, 'minItems', obj209) .
member(obj210, '@id', 'jsonschema:items') .
member(obj210, '@type', '@id') .
member(obj202, 'items', obj210) .
member(obj211, '@id', 'jsonschema:required') .
member(obj211, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj211, '@container', '@set') .
member(obj202, 'required', obj211) .
member(obj212, '@id', 'jsonschema:enum') .
member(obj212, '@type', '@id') .
member(obj212, '@container', '@set') .
member(obj202, 'enum', obj212) .
member(obj213, '@id', 'jsonschema:const') .
member(obj202, 'const', obj213) .
member(obj214, '@id', 'jsonschema:unit') .
member(obj202, 'unit', obj214) .
member(obj215, '@id', 'jsonschema:oneOf') .
member(obj215, '@container', '@set') .
member(obj202, 'oneOf', obj215) .
member(obj216, '@id', 'rdf:type') .
member(obj216, '@type', '@vocab') .
member(obj202, 'type', obj216) .
member(obj202, 'object', 'jsonschema:ObjectSchema') .
member(obj202, 'array', 'jsonschema:ArraySchema') .
member(obj202, 'boolean', 'jsonschema:BooleanSchema') .
member(obj202, 'string', 'jsonschema:StringSchema') .
member(obj202, 'number', 'jsonschema:NumberSchema') .
member(obj202, 'integer', 'jsonschema:IntegerSchema') .
member(obj202, 'null', 'jsonschema:NullSchema') .
member(obj217, '@id', 'jsonschema:properties') .
member(obj217, '@type', '@id') .
member(obj217, '@container', '@index') .
member(obj202, 'properties', obj217) .
member(obj201, '@context', obj202) .
member(obj89, 'subscription', obj201) .
member(obj218, '@id', 'td:hasNotificationSchema') .
member(obj218, '@type', '@id') .
member(obj219, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj219, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj219, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj219, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj219, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj220, '@id', 'jsonschema:DataSchema') .
member(obj219, 'DataSchema', obj220) .
member(obj221, '@id', 'jsonschema:readOnly') .
member(obj221, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj219, 'readOnly', obj221) .
member(obj222, '@id', 'jsonschema:writeOnly') .
member(obj222, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj219, 'writeOnly', obj222) .
member(obj223, '@id', 'jsonschema:maximum') .
member(obj219, 'maximum', obj223) .
member(obj224, '@id', 'jsonschema:minimum') .
member(obj219, 'minimum', obj224) .
member(obj225, '@id', 'jsonschema:maxItems') .
member(obj225, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj219, 'maxItems', obj225) .
member(obj226, '@id', 'jsonschema:minItems') .
member(obj226, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj219, 'minItems', obj226) .
member(obj227, '@id', 'jsonschema:items') .
member(obj227, '@type', '@id') .
member(obj219, 'items', obj227) .
member(obj228, '@id', 'jsonschema:required') .
member(obj228, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj228, '@container', '@set') .
member(obj219, 'required', obj228) .
member(obj229, '@id', 'jsonschema:enum') .
member(obj229, '@type', '@id') .
member(obj229, '@container', '@set') .
member(obj219, 'enum', obj229) .
member(obj230, '@id', 'jsonschema:const') .
member(obj219, 'const', obj230) .
member(obj231, '@id', 'jsonschema:unit') .
member(obj219, 'unit', obj231) .
member(obj232, '@id', 'jsonschema:oneOf') .
member(obj232, '@container', '@set') .
member(obj219, 'oneOf', obj232) .
member(obj233, '@id', 'rdf:type') .
member(obj233, '@type', '@vocab') .
member(obj219, 'type', obj233) .
member(obj219, 'object', 'jsonschema:ObjectSchema') .
member(obj219, 'array', 'jsonschema:ArraySchema') .
member(obj219, 'boolean', 'jsonschema:BooleanSchema') .
member(obj219, 'string', 'jsonschema:StringSchema') .
member(obj219, 'number', 'jsonschema:NumberSchema') .
member(obj219, 'integer', 'jsonschema:IntegerSchema') .
member(obj219, 'null', 'jsonschema:NullSchema') .
member(obj234, '@id', 'jsonschema:properties') .
member(obj234, '@type', '@id') .
member(obj234, '@container', '@index') .
member(obj219, 'properties', obj234) .
member(obj218, '@context', obj219) .
member(obj89, 'data', obj218) .
member(obj235, '@id', 'td:hasCancellationSchema') .
member(obj235, '@type', '@id') .
member(obj236, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj236, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj236, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj236, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj236, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj237, '@id', 'jsonschema:DataSchema') .
member(obj236, 'DataSchema', obj237) .
member(obj238, '@id', 'jsonschema:readOnly') .
member(obj238, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj236, 'readOnly', obj238) .
member(obj239, '@id', 'jsonschema:writeOnly') .
member(obj239, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj236, 'writeOnly', obj239) .
member(obj240, '@id', 'jsonschema:maximum') .
member(obj236, 'maximum', obj240) .
member(obj241, '@id', 'jsonschema:minimum') .
member(obj236, 'minimum', obj241) .
member(obj242, '@id', 'jsonschema:maxItems') .
member(obj242, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj236, 'maxItems', obj242) .
member(obj243, '@id', 'jsonschema:minItems') .
member(obj243, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj236, 'minItems', obj243) .
member(obj244, '@id', 'jsonschema:items') .
member(obj244, '@type', '@id') .
member(obj236, 'items', obj244) .
member(obj245, '@id', 'jsonschema:required') .
member(obj245, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj245, '@container', '@set') .
member(obj236, 'required', obj245) .
member(obj246, '@id', 'jsonschema:enum') .
member(obj246, '@type', '@id') .
member(obj246, '@container', '@set') .
member(obj236, 'enum', obj246) .
member(obj247, '@id', 'jsonschema:const') .
member(obj236, 'const', obj247) .
member(obj248, '@id', 'jsonschema:unit') .
member(obj236, 'unit', obj248) .
member(obj249, '@id', 'jsonschema:oneOf') .
member(obj249, '@container', '@set') .
member(obj236, 'oneOf', obj249) .
member(obj250, '@id', 'rdf:type') .
member(obj250, '@type', '@vocab') .
member(obj236, 'type', obj250) .
member(obj236, 'object', 'jsonschema:ObjectSchema') .
member(obj236, 'array', 'jsonschema:ArraySchema') .
member(obj236, 'boolean', 'jsonschema:BooleanSchema') .
member(obj236, 'string', 'jsonschema:StringSchema') .
member(obj236, 'number', 'jsonschema:NumberSchema') .
member(obj236, 'integer', 'jsonschema:IntegerSchema') .
member(obj236, 'null', 'jsonschema:NullSchema') .
member(obj251, '@id', 'jsonschema:properties') .
member(obj251, '@type', '@id') .
member(obj251, '@container', '@index') .
member(obj236, 'properties', obj251) .
member(obj235, '@context', obj236) .
member(obj89, 'cancellation', obj235) .
member(obj252, '@id', 'td:description') .
member(obj89, 'description', obj252) .
member(obj253, '@id', 'td:descriptions') .
member(obj253, '@container', '@language') .
member(obj89, 'descriptions', obj253) .
member(obj254, '@id', 'td:title') .
member(obj89, 'title', obj254) .
member(obj255, '@id', 'td:supportContact') .
member(obj89, 'support', obj255) .
member(obj256, '@id', 'td:defaultUnit') .
member(obj89, 'unit', obj256) .
member(obj89, '@version', 1.1) .
member(obj88, '@context', obj89) .
member(obj88, 'id', 'urn:dev:ops:32473-WoTLamp-1234') .
member(obj88, 'title', 'MyLampThing') .
member(obj258, 'scheme', 'basic') .
member(obj258, 'in', 'header') .
member(obj257, 'basic_sc', obj258) .
member(obj88, 'securityDefinitions', obj257) .
member(obj259, 0, 'basic_sc') .
member(obj88, 'security', obj259) .
member(obj261, 'type', 'string') .
member(obj263, 'href', 'https://mylamp.example.com/status') .
member(obj262, 0, obj263) .
member(obj261, 'forms', obj262) .
member(obj260, 'status', obj261) .
member(obj88, 'properties', obj260) .
member(obj267, 'href', 'https://mylamp.example.com/toggle') .
member(obj266, 0, obj267) .
member(obj265, 'forms', obj266) .
member(obj264, 'toggle', obj265) .
member(obj88, 'actions', obj264) .
member(obj270, 'type', 'string') .
member(obj269, 'data', obj270) .
member(obj272, 'href', 'https://mylamp.example.com/oh') .
member(obj272, 'subprotocol', 'longpoll') .
member(obj271, 0, obj272) .
member(obj269, 'forms', obj271) .
member(obj268, 'overheating', obj269) .
member(obj88, 'events', obj268) .
root('td.jsonld', obj88) .
member(obj274, 'Restaurant', 'http://schema.org/Restaurant') .
member(obj274, 'Brewery', 'http://schema.org/Brewery') .
member(obj273, '@context', obj274) .
member(obj273, '@id', 'http://example.org/places#BrewEats') .
member(obj275, 0, 'Restaurant') .
member(obj275, 1, 'Brewery') .
member(obj273, '@type', obj275) .
root('type-array-ctx.jsonld', obj273) .
member(obj276, '@id', 'http://example.org/places#BrewEats') .
member(obj277, 0, 'http://schema.org/Restaurant') .
member(obj277, 1, 'http://schema.org/Brewery') .
member(obj276, '@type', obj277) .
root('type-array.jsonld', obj276) .
member(obj279, 'foaf', 'http://xmlns.com/foaf/0.1/') .
member(obj280, '@id', 'http://xmlns.com/foaf/0.1/age') .
member(obj280, '@type', 'xsd:integer') .
member(obj279, 'foaf:age', obj280) .
member(obj281, '@type', '@id') .
member(obj279, 'http://xmlns.com/foaf/0.1/homepage', obj281) .
member(obj278, '@context', obj279) .
member(obj278, 'foaf:name', 'John Smith') .
member(obj278, 'foaf:age', '41') .
member(obj282, 0, 'http://personal.example.org/') .
member(obj282, 1, 'http://work.example.com/jsmith/') .
member(obj278, 'http://xmlns.com/foaf/0.1/homepage', obj282) .
root('type-coercion-ctx.jsonld', obj278) .
member(obj284, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj284, 'name', 'http://xmlns.com/foaf/0.1/name') .
member(obj285, '@id', 'http://xmlns.com/foaf/0.1/age') .
member(obj285, '@type', 'xsd:integer') .
member(obj284, 'age', obj285) .
member(obj286, '@id', 'http://xmlns.com/foaf/0.1/homepage') .
member(obj286, '@type', '@id') .
member(obj284, 'homepage', obj286) .
member(obj283, '@context', obj284) .
member(obj283, '@id', 'http://example.com/people#john') .
member(obj283, 'name', 'John Smith') .
member(obj283, 'age', '41') .
member(obj287, 0, 'http://personal.example.org/') .
member(obj287, 1, 'http://work.example.com/jsmith/') .
member(obj283, 'homepage', obj287) .
root('type-coercion.jsonld', obj283) .
member(obj290, '@id', 'http://purl.org/dc/terms/modified') .
member(obj290, '@type', 'http://www.w3.org/2001/XMLSchema#dateTime') .
member(obj289, 'modified', obj290) .
member(obj288, '@context', obj289) .
member(obj288, '@id', 'http://example.com/docs/1') .
member(obj288, 'modified', '2010-05-29T14:17:39+02:00') .
root('type-ctx.jsonld', obj288) .
member(obj291, '@id', 'http://example.org/places#BrewEats') .
member(obj291, '@type', 'http://schema.org/Restaurant') .
root('type.jsonld', obj291) .
member(obj293, '@vocab', 'http://schema.org/') .
member(obj293, 'databaseId', obj294) .
member(obj292, '@context', obj293) .
member(obj292, '@id', 'http://example.org/places#BrewEats') .
member(obj292, '@type', 'Restaurant') .
member(obj292, 'name', 'Brew Eats') .
member(obj292, 'databaseId', '23987520') .
root('vocab-null.jsonld', obj292) .
member(obj296, '@vocab', 'http://schema.org/') .
member(obj295, '@context', obj296) .
member(obj295, '@id', 'http://example.org/places#BrewEats') .
member(obj295, '@type', 'Restaurant') .
member(obj295, 'name', 'Brew Eats') .
root('vocab.jsonld', obj295) .
