member(obj1, 'name', 'http://schema.org/name') .
member(obj2, '@id', 'http://schema.org/image') .
member(obj2, '@type', '@id') .
member(obj1, 'image', obj2) .
member(obj3, '@id', 'http://schema.org/url') .
member(obj3, '@type', '@id') .
member(obj1, 'homepage', obj3) .
member(obj0, '@context', obj1) .
member(obj0, 'name', 'Manu Sporny') .
member(obj0, 'homepage', 'http://manu.sporny.org/') .
member(obj0, 'image', 'http://manu.sporny.org/images/manu.png') .
root('ctx-inline.jsonld', obj0) .
member(obj4, '@context', 'http://json-ld.org/contexts/person.jsonld') .
member(obj4, 'name', 'Manu Sporny') .
member(obj4, 'homepage', 'http://manu.sporny.org/') .
member(obj4, 'image', 'http://manu.sporny.org/images/manu.png') .
root('ctx-remote.jsonld', obj4) .
member(obj5, 'http://schema.org/name', 'Manu Sporny') .
member(obj6, '@id', 'http://manu.sporny.org/') .
member(obj5, 'http://schema.org/url', obj6) .
member(obj7, '@id', 'http://manu.sporny.org/images/manu.png') .
member(obj5, 'http://schema.org/image', obj7) .
root('intro.jsonld', obj5) .
member(obj9, 'name', 'http://schema.org/name') .
member(obj8, '@context', obj9) .
member(obj8, 'name', 'Manu Sporny') .
member(obj8, 'status', 'trollin') .
root('iris-ignored.jsonld', obj8) .
member(obj11, 'name', 'http://schema.org/name') .
member(obj10, '@context', obj11) .
member(obj10, '@id', 'http://me.markus-lanthaler.com/') .
member(obj10, 'name', 'Markus Lanthaler') .
root('node-id.jsonld', obj10) .
member(obj13, 'Person', 'http://schema.org/Person') .
member(obj13, 'name', 'http://schema.org/name') .
member(obj13, 'jobTitle', 'http://schema.org/jobTitle') .
member(obj13, 'telephone', 'http://schema.org/telephone') .
member(obj14, '@id', 'http://schema.org/url') .
member(obj14, '@type', '@id') .
member(obj13, 'url', obj14) .
member(obj12, '@context', obj13) .
member(obj12, '@type', 'Person') .
member(obj12, 'name', 'Jane Doe') .
member(obj12, 'jobTitle', 'Professor') .
member(obj12, 'telephone', '(425) 123-4567') .
member(obj12, 'url', 'http://www.janedoe.com') .
root('person.jsonld', obj12) .
member(obj16, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj16, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj16, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj16, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj16, 'rdfs', 'http://www.w3.org/2000/01/rdf-schema#') .
member(obj16, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj17, '@id', 'http://purl.org/dc/terms/license') .
member(obj16, 'license', obj17) .
member(obj16, 'id', '@id') .
member(obj18, '@id', 'td:hasPropertyAffordance') .
member(obj18, '@type', '@id') .
member(obj18, '@container', '@index') .
member(obj19, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj19, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj19, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj19, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj19, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj20, '@id', 'jsonschema:DataSchema') .
member(obj19, 'DataSchema', obj20) .
member(obj21, '@id', 'jsonschema:readOnly') .
member(obj21, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj19, 'readOnly', obj21) .
member(obj22, '@id', 'jsonschema:writeOnly') .
member(obj22, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj19, 'writeOnly', obj22) .
member(obj23, '@id', 'jsonschema:maximum') .
member(obj19, 'maximum', obj23) .
member(obj24, '@id', 'jsonschema:minimum') .
member(obj19, 'minimum', obj24) .
member(obj25, '@id', 'jsonschema:maxItems') .
member(obj25, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj19, 'maxItems', obj25) .
member(obj26, '@id', 'jsonschema:minItems') .
member(obj26, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj19, 'minItems', obj26) .
member(obj27, '@id', 'jsonschema:items') .
member(obj27, '@type', '@id') .
member(obj19, 'items', obj27) .
member(obj28, '@id', 'jsonschema:required') .
member(obj28, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj28, '@container', '@set') .
member(obj19, 'required', obj28) .
member(obj29, '@id', 'jsonschema:enum') .
member(obj29, '@type', '@id') .
member(obj29, '@container', '@set') .
member(obj19, 'enum', obj29) .
member(obj30, '@id', 'jsonschema:const') .
member(obj19, 'const', obj30) .
member(obj31, '@id', 'jsonschema:unit') .
member(obj19, 'unit', obj31) .
member(obj32, '@id', 'jsonschema:oneOf') .
member(obj32, '@container', '@set') .
member(obj19, 'oneOf', obj32) .
member(obj33, '@id', 'rdf:type') .
member(obj33, '@type', '@vocab') .
member(obj19, 'type', obj33) .
member(obj19, 'object', 'jsonschema:ObjectSchema') .
member(obj19, 'array', 'jsonschema:ArraySchema') .
member(obj19, 'boolean', 'jsonschema:BooleanSchema') .
member(obj19, 'string', 'jsonschema:StringSchema') .
member(obj19, 'number', 'jsonschema:NumberSchema') .
member(obj19, 'integer', 'jsonschema:IntegerSchema') .
member(obj19, 'null', 'jsonschema:NullSchema') .
member(obj34, '@id', 'jsonschema:properties') .
member(obj34, '@type', '@id') .
member(obj34, '@container', '@index') .
member(obj19, 'properties', obj34) .
member(obj18, '@context', obj19) .
member(obj16, 'properties', obj18) .
member(obj35, '@id', 'td:hasActionAffordance') .
member(obj35, '@type', '@id') .
member(obj35, '@container', '@index') .
member(obj16, 'actions', obj35) .
member(obj36, '@id', 'td:hasEventAffordance') .
member(obj36, '@type', '@id') .
member(obj36, '@container', '@index') .
member(obj16, 'events', obj36) .
member(obj37, '@id', 'td:hasSecurityConfiguration') .
member(obj37, '@type', '@id') .
member(obj37, '@container', '@set') .
member(obj38, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj38, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj38, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj38, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj38, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj39, '@id', 'wotsec:in') .
member(obj38, 'in', obj39) .
member(obj40, '@id', 'wotsec:authorization') .
member(obj38, 'authorization', obj40) .
member(obj41, '@id', 'wotsec:token') .
member(obj38, 'token', obj41) .
member(obj42, '@id', 'wotsec:refresh') .
member(obj38, 'refresh', obj42) .
member(obj43, '@id', 'wotsec:proxy') .
member(obj38, 'proxy', obj43) .
member(obj44, '@id', 'wotsec:scopes') .
member(obj44, '@container', '@set') .
member(obj38, 'scopes', obj44) .
member(obj45, '@id', 'wotsec:flow') .
member(obj38, 'flow', obj45) .
member(obj46, '@id', 'wotsec:qop') .
member(obj38, 'qop', obj46) .
member(obj47, '@id', 'wotsec:alg') .
member(obj38, 'alg', obj47) .
member(obj48, '@id', 'wotsec:format') .
member(obj38, 'format', obj48) .
member(obj49, '@id', 'wotsec:identity') .
member(obj38, 'identity', obj49) .
member(obj50, '@id', 'rdf:type') .
member(obj50, '@type', '@vocab') .
member(obj38, 'scheme', obj50) .
member(obj38, 'nosec', 'wotsec:NoSecurityScheme') .
member(obj38, 'basic', 'wotsec:BasicSecurityScheme') .
member(obj38, 'digest', 'wotsec:DigestSecurityScheme') .
member(obj38, 'apikey', 'wotsec:APIKeySecurityScheme') .
member(obj38, 'bearer', 'wotsec:BearerSecurityScheme') .
member(obj38, 'cert', 'wotsec:CertSecurityScheme') .
member(obj38, 'psk', 'wotsec:PSKSecurityScheme') .
member(obj38, 'public', 'wotsec:PublicSecurityScheme') .
member(obj38, 'pop', 'wotsec:PoPSecurityScheme') .
member(obj38, 'oauth2', 'wotsec:OAuth2SecurityScheme') .
member(obj37, '@context', obj38) .
member(obj16, 'security', obj37) .
member(obj51, '@id', 'td:securityDefinitions') .
member(obj51, '@type', '@id') .
member(obj51, '@container', '@index') .
member(obj16, 'securityDefinitions', obj51) .
member(obj52, '@id', 'td:Thing') .
member(obj16, 'Thing', obj52) .
member(obj53, '@id', 'td:EventAffordance') .
member(obj16, 'EventAffordance', obj53) .
member(obj54, '@id', 'td:baseUri') .
member(obj54, '@type', 'xsd:anyURI') .
member(obj16, 'base', obj54) .
member(obj55, '@id', 'td:name') .
member(obj16, 'name', obj55) .
member(obj56, '@id', 'td:created') .
member(obj16, 'created', obj56) .
member(obj57, '@id', 'td:modified') .
member(obj16, 'modified', obj57) .
member(obj58, '@id', 'td:isObservable') .
member(obj58, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj16, 'observable', obj58) .
member(obj59, '@id', 'td:VersionInfo') .
member(obj16, 'VersionInfo', obj59) .
member(obj60, '@id', 'td:PropertyAffordance') .
member(obj16, 'PropertyAffordance', obj60) .
member(obj61, '@id', 'td:hasForm') .
member(obj61, '@type', '@id') .
member(obj61, '@container', '@set') .
member(obj62, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj62, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj62, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj62, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj62, 'rdfs', 'http://www.w3.org/2000/01/rdf-schema#') .
member(obj62, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj63, '@id', 'hyperm:Link') .
member(obj62, 'Link', obj63) .
member(obj64, '@id', 'hyperm:Form') .
member(obj62, 'Form', obj64) .
member(obj65, '@id', 'hyperm:forOperationType') .
member(obj65, '@container', '@set') .
member(obj62, 'op', obj65) .
member(obj66, '@id', 'hyperm:forSubProtocol') .
member(obj62, 'subprotocol', obj66) .
member(obj67, '@id', 'hyperm:forContentType') .
member(obj67, '@type', 'xsd:string') .
member(obj62, 'contentType', obj67) .
member(obj68, '@id', 'hyperm:forContentCoding') .
member(obj68, '@type', 'xsd:string') .
member(obj62, 'contentCoding', obj68) .
member(obj69, '@id', 'hyperm:hasAnchor') .
member(obj62, 'anchor', obj69) .
member(obj70, '@id', 'hyperm:hasTarget') .
member(obj62, 'href', obj70) .
member(obj71, '@id', 'hyperm:hasRelationType') .
member(obj62, 'rel', obj71) .
member(obj72, '@id', 'hyperm:hintsAtMediaType') .
member(obj62, 'type', obj72) .
member(obj73, '@id', 'hyperm:returns') .
member(obj62, 'response', obj73) .
member(obj61, '@context', obj62) .
member(obj16, 'forms', obj61) .
member(obj74, '@id', 'td:versionInfo') .
member(obj74, '@type', '@id') .
member(obj16, 'version', obj74) .
member(obj75, '@id', 'td:hasLink') .
member(obj75, '@type', '@id') .
member(obj75, '@container', '@set') .
member(obj76, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj76, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj76, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj76, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj76, 'rdfs', 'http://www.w3.org/2000/01/rdf-schema#') .
member(obj76, 'xsd', 'http://www.w3.org/2001/XMLSchema#') .
member(obj77, '@id', 'hyperm:Link') .
member(obj76, 'Link', obj77) .
member(obj78, '@id', 'hyperm:Form') .
member(obj76, 'Form', obj78) .
member(obj79, '@id', 'hyperm:forOperationType') .
member(obj79, '@container', '@set') .
member(obj76, 'op', obj79) .
member(obj80, '@id', 'hyperm:forSubProtocol') .
member(obj76, 'subprotocol', obj80) .
member(obj81, '@id', 'hyperm:forContentType') .
member(obj81, '@type', 'xsd:string') .
member(obj76, 'contentType', obj81) .
member(obj82, '@id', 'hyperm:forContentCoding') .
member(obj82, '@type', 'xsd:string') .
member(obj76, 'contentCoding', obj82) .
member(obj83, '@id', 'hyperm:hasAnchor') .
member(obj76, 'anchor', obj83) .
member(obj84, '@id', 'hyperm:hasTarget') .
member(obj76, 'href', obj84) .
member(obj85, '@id', 'hyperm:hasRelationType') .
member(obj76, 'rel', obj85) .
member(obj86, '@id', 'hyperm:hintsAtMediaType') .
member(obj76, 'type', obj86) .
member(obj87, '@id', 'hyperm:returns') .
member(obj76, 'response', obj87) .
member(obj75, '@context', obj76) .
member(obj16, 'links', obj75) .
member(obj88, '@id', 'td:hasUriTemplateVariable') .
member(obj88, '@container', '@index') .
member(obj16, 'uriVariables', obj88) .
member(obj89, '@id', 'td:isSafe') .
member(obj16, 'safe', obj89) .
member(obj90, '@id', 'td:isIdempotent') .
member(obj16, 'idempotent', obj90) .
member(obj91, '@id', 'td:instance') .
member(obj16, 'instance', obj91) .
member(obj92, '@id', 'td:InteractionAffordance') .
member(obj16, 'InteractionAffordance', obj92) .
member(obj93, '@id', 'td:ActionAffordance') .
member(obj16, 'ActionAffordance', obj93) .
member(obj94, '@id', 'td:hasInputSchema') .
member(obj94, '@type', '@id') .
member(obj95, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj95, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj95, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj95, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj95, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj96, '@id', 'jsonschema:DataSchema') .
member(obj95, 'DataSchema', obj96) .
member(obj97, '@id', 'jsonschema:readOnly') .
member(obj97, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj95, 'readOnly', obj97) .
member(obj98, '@id', 'jsonschema:writeOnly') .
member(obj98, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj95, 'writeOnly', obj98) .
member(obj99, '@id', 'jsonschema:maximum') .
member(obj95, 'maximum', obj99) .
member(obj100, '@id', 'jsonschema:minimum') .
member(obj95, 'minimum', obj100) .
member(obj101, '@id', 'jsonschema:maxItems') .
member(obj101, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj95, 'maxItems', obj101) .
member(obj102, '@id', 'jsonschema:minItems') .
member(obj102, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj95, 'minItems', obj102) .
member(obj103, '@id', 'jsonschema:items') .
member(obj103, '@type', '@id') .
member(obj95, 'items', obj103) .
member(obj104, '@id', 'jsonschema:required') .
member(obj104, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj104, '@container', '@set') .
member(obj95, 'required', obj104) .
member(obj105, '@id', 'jsonschema:enum') .
member(obj105, '@type', '@id') .
member(obj105, '@container', '@set') .
member(obj95, 'enum', obj105) .
member(obj106, '@id', 'jsonschema:const') .
member(obj95, 'const', obj106) .
member(obj107, '@id', 'jsonschema:unit') .
member(obj95, 'unit', obj107) .
member(obj108, '@id', 'jsonschema:oneOf') .
member(obj108, '@container', '@set') .
member(obj95, 'oneOf', obj108) .
member(obj109, '@id', 'rdf:type') .
member(obj109, '@type', '@vocab') .
member(obj95, 'type', obj109) .
member(obj95, 'object', 'jsonschema:ObjectSchema') .
member(obj95, 'array', 'jsonschema:ArraySchema') .
member(obj95, 'boolean', 'jsonschema:BooleanSchema') .
member(obj95, 'string', 'jsonschema:StringSchema') .
member(obj95, 'number', 'jsonschema:NumberSchema') .
member(obj95, 'integer', 'jsonschema:IntegerSchema') .
member(obj95, 'null', 'jsonschema:NullSchema') .
member(obj110, '@id', 'jsonschema:properties') .
member(obj110, '@type', '@id') .
member(obj110, '@container', '@index') .
member(obj95, 'properties', obj110) .
member(obj94, '@context', obj95) .
member(obj16, 'input', obj94) .
member(obj111, '@id', 'td:hasOutputSchema') .
member(obj111, '@type', '@id') .
member(obj112, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj112, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj112, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj112, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj112, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj113, '@id', 'jsonschema:DataSchema') .
member(obj112, 'DataSchema', obj113) .
member(obj114, '@id', 'jsonschema:readOnly') .
member(obj114, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj112, 'readOnly', obj114) .
member(obj115, '@id', 'jsonschema:writeOnly') .
member(obj115, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj112, 'writeOnly', obj115) .
member(obj116, '@id', 'jsonschema:maximum') .
member(obj112, 'maximum', obj116) .
member(obj117, '@id', 'jsonschema:minimum') .
member(obj112, 'minimum', obj117) .
member(obj118, '@id', 'jsonschema:maxItems') .
member(obj118, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj112, 'maxItems', obj118) .
member(obj119, '@id', 'jsonschema:minItems') .
member(obj119, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj112, 'minItems', obj119) .
member(obj120, '@id', 'jsonschema:items') .
member(obj120, '@type', '@id') .
member(obj112, 'items', obj120) .
member(obj121, '@id', 'jsonschema:required') .
member(obj121, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj121, '@container', '@set') .
member(obj112, 'required', obj121) .
member(obj122, '@id', 'jsonschema:enum') .
member(obj122, '@type', '@id') .
member(obj122, '@container', '@set') .
member(obj112, 'enum', obj122) .
member(obj123, '@id', 'jsonschema:const') .
member(obj112, 'const', obj123) .
member(obj124, '@id', 'jsonschema:unit') .
member(obj112, 'unit', obj124) .
member(obj125, '@id', 'jsonschema:oneOf') .
member(obj125, '@container', '@set') .
member(obj112, 'oneOf', obj125) .
member(obj126, '@id', 'rdf:type') .
member(obj126, '@type', '@vocab') .
member(obj112, 'type', obj126) .
member(obj112, 'object', 'jsonschema:ObjectSchema') .
member(obj112, 'array', 'jsonschema:ArraySchema') .
member(obj112, 'boolean', 'jsonschema:BooleanSchema') .
member(obj112, 'string', 'jsonschema:StringSchema') .
member(obj112, 'number', 'jsonschema:NumberSchema') .
member(obj112, 'integer', 'jsonschema:IntegerSchema') .
member(obj112, 'null', 'jsonschema:NullSchema') .
member(obj127, '@id', 'jsonschema:properties') .
member(obj127, '@type', '@id') .
member(obj127, '@container', '@index') .
member(obj112, 'properties', obj127) .
member(obj111, '@context', obj112) .
member(obj16, 'output', obj111) .
member(obj128, '@id', 'td:hasSubscriptionSchema') .
member(obj128, '@type', '@id') .
member(obj129, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj129, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj129, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj129, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj129, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj130, '@id', 'jsonschema:DataSchema') .
member(obj129, 'DataSchema', obj130) .
member(obj131, '@id', 'jsonschema:readOnly') .
member(obj131, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj129, 'readOnly', obj131) .
member(obj132, '@id', 'jsonschema:writeOnly') .
member(obj132, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj129, 'writeOnly', obj132) .
member(obj133, '@id', 'jsonschema:maximum') .
member(obj129, 'maximum', obj133) .
member(obj134, '@id', 'jsonschema:minimum') .
member(obj129, 'minimum', obj134) .
member(obj135, '@id', 'jsonschema:maxItems') .
member(obj135, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj129, 'maxItems', obj135) .
member(obj136, '@id', 'jsonschema:minItems') .
member(obj136, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj129, 'minItems', obj136) .
member(obj137, '@id', 'jsonschema:items') .
member(obj137, '@type', '@id') .
member(obj129, 'items', obj137) .
member(obj138, '@id', 'jsonschema:required') .
member(obj138, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj138, '@container', '@set') .
member(obj129, 'required', obj138) .
member(obj139, '@id', 'jsonschema:enum') .
member(obj139, '@type', '@id') .
member(obj139, '@container', '@set') .
member(obj129, 'enum', obj139) .
member(obj140, '@id', 'jsonschema:const') .
member(obj129, 'const', obj140) .
member(obj141, '@id', 'jsonschema:unit') .
member(obj129, 'unit', obj141) .
member(obj142, '@id', 'jsonschema:oneOf') .
member(obj142, '@container', '@set') .
member(obj129, 'oneOf', obj142) .
member(obj143, '@id', 'rdf:type') .
member(obj143, '@type', '@vocab') .
member(obj129, 'type', obj143) .
member(obj129, 'object', 'jsonschema:ObjectSchema') .
member(obj129, 'array', 'jsonschema:ArraySchema') .
member(obj129, 'boolean', 'jsonschema:BooleanSchema') .
member(obj129, 'string', 'jsonschema:StringSchema') .
member(obj129, 'number', 'jsonschema:NumberSchema') .
member(obj129, 'integer', 'jsonschema:IntegerSchema') .
member(obj129, 'null', 'jsonschema:NullSchema') .
member(obj144, '@id', 'jsonschema:properties') .
member(obj144, '@type', '@id') .
member(obj144, '@container', '@index') .
member(obj129, 'properties', obj144) .
member(obj128, '@context', obj129) .
member(obj16, 'subscription', obj128) .
member(obj145, '@id', 'td:hasNotificationSchema') .
member(obj145, '@type', '@id') .
member(obj146, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj146, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj146, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj146, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj146, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj147, '@id', 'jsonschema:DataSchema') .
member(obj146, 'DataSchema', obj147) .
member(obj148, '@id', 'jsonschema:readOnly') .
member(obj148, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj146, 'readOnly', obj148) .
member(obj149, '@id', 'jsonschema:writeOnly') .
member(obj149, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj146, 'writeOnly', obj149) .
member(obj150, '@id', 'jsonschema:maximum') .
member(obj146, 'maximum', obj150) .
member(obj151, '@id', 'jsonschema:minimum') .
member(obj146, 'minimum', obj151) .
member(obj152, '@id', 'jsonschema:maxItems') .
member(obj152, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj146, 'maxItems', obj152) .
member(obj153, '@id', 'jsonschema:minItems') .
member(obj153, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj146, 'minItems', obj153) .
member(obj154, '@id', 'jsonschema:items') .
member(obj154, '@type', '@id') .
member(obj146, 'items', obj154) .
member(obj155, '@id', 'jsonschema:required') .
member(obj155, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj155, '@container', '@set') .
member(obj146, 'required', obj155) .
member(obj156, '@id', 'jsonschema:enum') .
member(obj156, '@type', '@id') .
member(obj156, '@container', '@set') .
member(obj146, 'enum', obj156) .
member(obj157, '@id', 'jsonschema:const') .
member(obj146, 'const', obj157) .
member(obj158, '@id', 'jsonschema:unit') .
member(obj146, 'unit', obj158) .
member(obj159, '@id', 'jsonschema:oneOf') .
member(obj159, '@container', '@set') .
member(obj146, 'oneOf', obj159) .
member(obj160, '@id', 'rdf:type') .
member(obj160, '@type', '@vocab') .
member(obj146, 'type', obj160) .
member(obj146, 'object', 'jsonschema:ObjectSchema') .
member(obj146, 'array', 'jsonschema:ArraySchema') .
member(obj146, 'boolean', 'jsonschema:BooleanSchema') .
member(obj146, 'string', 'jsonschema:StringSchema') .
member(obj146, 'number', 'jsonschema:NumberSchema') .
member(obj146, 'integer', 'jsonschema:IntegerSchema') .
member(obj146, 'null', 'jsonschema:NullSchema') .
member(obj161, '@id', 'jsonschema:properties') .
member(obj161, '@type', '@id') .
member(obj161, '@container', '@index') .
member(obj146, 'properties', obj161) .
member(obj145, '@context', obj146) .
member(obj16, 'data', obj145) .
member(obj162, '@id', 'td:hasCancellationSchema') .
member(obj162, '@type', '@id') .
member(obj163, 'td', 'https://www.w3.org/2019/wot/td#') .
member(obj163, 'jsonschema', 'https://www.w3.org/2019/wot/json-schema#') .
member(obj163, 'wotsec', 'https://www.w3.org/2019/wot/security#') .
member(obj163, 'hyperm', 'https://www.w3.org/2019/wot/hypermedia#') .
member(obj163, 'rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#') .
member(obj164, '@id', 'jsonschema:DataSchema') .
member(obj163, 'DataSchema', obj164) .
member(obj165, '@id', 'jsonschema:readOnly') .
member(obj165, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj163, 'readOnly', obj165) .
member(obj166, '@id', 'jsonschema:writeOnly') .
member(obj166, '@type', 'http://www.w3.org/2001/XMLSchema#boolean') .
member(obj163, 'writeOnly', obj166) .
member(obj167, '@id', 'jsonschema:maximum') .
member(obj163, 'maximum', obj167) .
member(obj168, '@id', 'jsonschema:minimum') .
member(obj163, 'minimum', obj168) .
member(obj169, '@id', 'jsonschema:maxItems') .
member(obj169, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj163, 'maxItems', obj169) .
member(obj170, '@id', 'jsonschema:minItems') .
member(obj170, '@type', 'http://www.w3.org/2001/XMLSchema#decimal') .
member(obj163, 'minItems', obj170) .
member(obj171, '@id', 'jsonschema:items') .
member(obj171, '@type', '@id') .
member(obj163, 'items', obj171) .
member(obj172, '@id', 'jsonschema:required') .
member(obj172, '@type', 'http://www.w3.org/2001/XMLSchema#string') .
member(obj172, '@container', '@set') .
member(obj163, 'required', obj172) .
member(obj173, '@id', 'jsonschema:enum') .
member(obj173, '@type', '@id') .
member(obj173, '@container', '@set') .
member(obj163, 'enum', obj173) .
member(obj174, '@id', 'jsonschema:const') .
member(obj163, 'const', obj174) .
member(obj175, '@id', 'jsonschema:unit') .
member(obj163, 'unit', obj175) .
member(obj176, '@id', 'jsonschema:oneOf') .
member(obj176, '@container', '@set') .
member(obj163, 'oneOf', obj176) .
member(obj177, '@id', 'rdf:type') .
member(obj177, '@type', '@vocab') .
member(obj163, 'type', obj177) .
member(obj163, 'object', 'jsonschema:ObjectSchema') .
member(obj163, 'array', 'jsonschema:ArraySchema') .
member(obj163, 'boolean', 'jsonschema:BooleanSchema') .
member(obj163, 'string', 'jsonschema:StringSchema') .
member(obj163, 'number', 'jsonschema:NumberSchema') .
member(obj163, 'integer', 'jsonschema:IntegerSchema') .
member(obj163, 'null', 'jsonschema:NullSchema') .
member(obj178, '@id', 'jsonschema:properties') .
member(obj178, '@type', '@id') .
member(obj178, '@container', '@index') .
member(obj163, 'properties', obj178) .
member(obj162, '@context', obj163) .
member(obj16, 'cancellation', obj162) .
member(obj179, '@id', 'td:description') .
member(obj16, 'description', obj179) .
member(obj180, '@id', 'td:descriptions') .
member(obj180, '@container', '@language') .
member(obj16, 'descriptions', obj180) .
member(obj181, '@id', 'td:title') .
member(obj16, 'title', obj181) .
member(obj182, '@id', 'td:supportContact') .
member(obj16, 'support', obj182) .
member(obj183, '@id', 'td:defaultUnit') .
member(obj16, 'unit', obj183) .
member(obj16, '@version', 1.1) .
member(obj15, '@context', obj16) .
member(obj15, 'id', 'urn:dev:ops:32473-WoTLamp-1234') .
member(obj15, 'title', 'MyLampThing') .
member(obj185, 'scheme', 'basic') .
member(obj185, 'in', 'header') .
member(obj184, 'basic_sc', obj185) .
member(obj15, 'securityDefinitions', obj184) .
member(obj186, 0, 'basic_sc') .
member(obj15, 'security', obj186) .
member(obj188, 'type', 'string') .
member(obj190, 'href', 'https://mylamp.example.com/status') .
member(obj189, 0, obj190) .
member(obj188, 'forms', obj189) .
member(obj187, 'status', obj188) .
member(obj15, 'properties', obj187) .
member(obj194, 'href', 'https://mylamp.example.com/toggle') .
member(obj193, 0, obj194) .
member(obj192, 'forms', obj193) .
member(obj191, 'toggle', obj192) .
member(obj15, 'actions', obj191) .
member(obj197, 'type', 'string') .
member(obj196, 'data', obj197) .
member(obj199, 'href', 'https://mylamp.example.com/oh') .
member(obj199, 'subprotocol', 'longpoll') .
member(obj198, 0, obj199) .
member(obj196, 'forms', obj198) .
member(obj195, 'overheating', obj196) .
member(obj15, 'events', obj195) .
root('td.jsonld', obj15) .
member(obj201, 'Restaurant', 'http://schema.org/Restaurant') .
member(obj201, 'Brewery', 'http://schema.org/Brewery') .
member(obj200, '@context', obj201) .
member(obj200, '@id', 'http://example.org/places#BrewEats') .
member(obj202, 0, 'Restaurant') .
member(obj202, 1, 'Brewery') .
member(obj200, '@type', obj202) .
root('type-array-ctx.jsonld', obj200) .
member(obj203, '@id', 'http://example.org/places#BrewEats') .
member(obj204, 0, 'http://schema.org/Restaurant') .
member(obj204, 1, 'http://schema.org/Brewery') .
member(obj203, '@type', obj204) .
root('type-array.jsonld', obj203) .
member(obj205, '@id', 'http://example.org/places#BrewEats') .
member(obj205, '@type', 'http://schema.org/Restaurant') .
root('type.jsonld', obj205) .
